"""Documentation page titles, mapped to their path under ``doc/``. **Generated file.**

Do not edit by hand: run ``poetry run python scripts/refresh_doc_pages.py`` from
``services/support-bot/``. ``tests/test_doc_pages.py`` rebuilds this from the real ``doc/`` tree and
fails when the two have drifted.

Keys are titles normalised by :func:`veaf_support_bot.doc_pages.normalize_title`; values are paths
relative to ``doc/``, which :func:`veaf_support_bot.doc_pages.page_url` turns into site addresses.
"""

from __future__ import annotations

from typing import Final

#: ``{language: {normalised title: path relative to doc/}}``.
PAGES_BY_TITLE: Final[dict[str, dict[str, str]]] = {
    "en": {
        'adopting a foothold mission onto the v6 toolchain (the "moulinette': "mission-maker/FOOTHOLD.en.md",
        "ai mission-editing assistant — action catalogue": "mission-maker/AI_ASSISTANT_CATALOG.en.md",
        "aliases reference": "ALIASES.en.md",
        "cli reference — `veaf-tools": "CLI_REFERENCE.en.md",
        "collect a map's airbases — step by step": "developer/capture-airbases.en.md",
        "combat zones": "mission-maker/concepts/combat-zones.en.md",
        "convert-other` — adopt a third-party mission onto v6": "mission-maker/CONVERT_OTHER.en.md",
        "custom scripts": "mission-maker/concepts/custom-scripts.en.md",
        "dcs radio frequency specifications": "mission-maker/dcs-radio-specs.en.md",
        "dcs reference data generators": "developer/dcs-data.en.md",
        "developer guide": "developer/README.en.md",
        "developer guide — veaf mission creation tools": "developer/GUIDE.en.md",
        "discover vmct in ten minutes": "mission-maker/DISCOVER.en.md",
        "dynamic slots": "mission-maker/concepts/dynamic-slots.en.md",
        "getting help": "SUPPORT.en.md",
        "install the ai mission-editing assistant": "mission-maker/AI_ASSISTANT_INSTALL.en.md",
        "migrating a mission to veaf mct v6": "mission-maker/MIGRATION_GUIDE.en.md",
        "mission maker guide": "mission-maker/README.en.md",
        "mission maker guide — veaf mission creation tools": "mission-maker/GUIDE.en.md",
        "mission.yaml reference": "MISSION_YAML_REFERENCE.en.md",
        "mission.yaml` and its modules": "mission-maker/concepts/mission-yaml.en.md",
        "per-type radio-preset projection": "developer/radio-preset-projection.en.md",
        "pilot guide": "pilot/README.en.md",
        "pilot guide — veaf mission creation tools": "pilot/GUIDE.en.md",
        "pipeline reference": "PIPELINE_REFERENCE.en.md",
        "radio presets": "mission-maker/concepts/radio-presets.en.md",
        "roadmap": "ROADMAP.en.md",
        "scripts reference — veaf lua modules": "mission-maker/scripts/README.en.md",
        "smoke harness — assert veaf inside a real dcs": "developer/smoke-harness.en.md",
        "spawnable groups": "mission-maker/concepts/spawnables.en.md",
        "testing guide": "TESTING.en.md",
        "the build": "mission-maker/concepts/build.en.md",
        "the cards — one concept, one page": "mission-maker/concepts/README.en.md",
        "the mission folder": "mission-maker/concepts/mission-folder.en.md",
        "tutorial — your first mission": "mission-maker/TUTORIAL.en.md",
        "veaf lua modules - complete api reference": "LUA_API_REFERENCE.en.md",
        "veaf mission creation tools — documentation": "index.en.md",
        "veaf tools — user and administrator guide": "TOOLS_REFERENCE.en.md",
        "veaf-logs — reading dcs logs": "mission-maker/LOGS.en.md",
        "veaf-mission-mcp` — llm-assisted mission-editing mcp server": "developer/mission-editing-mcp.en.md",
        "veaf-tools doctor` — paste block format": "developer/diagnostic-block.en.md",
        "veaf-tools mission export` — json contract for the bfr `dcs-mission-tools` plugin": "developer/export-json-contract.en.md",
        "veafairbases — airbase data and atc": "mission-maker/scripts/veafAirbases.en.md",
        "veafairwaves — wave-based air attacks": "mission-maker/scripts/veafAirWaves.en.md",
        "veafassets — tankers, awacs, and carriers": "mission-maker/scripts/veafAssets.en.md",
        "veafassist — guided checklists": "mission-maker/scripts/veafAssist.en.md",
        "veafcarrieroperations — carrier recovery management": "mission-maker/scripts/veafCarrierOperations.en.md",
        "veafcasmission — cas training generator": "mission-maker/scripts/veafCasMission.en.md",
        "veafcombatmission — the missions menu": "mission-maker/scripts/veafCombatMission.en.md",
        "veafcombatzone — activatable combat zones": "mission-maker/scripts/veafCombatZone.en.md",
        "veafcommands — the marker-command dispatcher": "mission-maker/scripts/veafCommands.en.md",
        "veafgrass — grass airstrip configuration": "mission-maker/scripts/veafGrass.en.md",
        "veafgroundai — driving an artillery battery from a marker": "mission-maker/scripts/veafGroundAI.en.md",
        "veafi18n — the in-game message catalogue": "mission-maker/scripts/veafI18n.en.md",
        "veafinterpreter — unit-embedded commands": "mission-maker/scripts/veafInterpreter.en.md",
        "veafmissileguardian — missile interception": "mission-maker/scripts/veafMissileGuardian.en.md",
        "veafmove — unit movement and tanker route management": "mission-maker/scripts/veafMove.en.md",
        "veafnamedpoints — named map positions": "mission-maker/scripts/veafNamedPoints.en.md",
        "veafqramanager — quick reaction alert": "mission-maker/scripts/veafQraManager.en.md",
        "veafradio — f10 radio menu builder": "mission-maker/scripts/veafRadio.en.md",
        "veafsanctuary — protected zones": "mission-maker/scripts/veafSanctuary.en.md",
        "veafsecurity — role-based permissions": "mission-maker/scripts/veafSecurity.en.md",
        "veafserverhook — veaf server hook": "mission-maker/scripts/veafServerHook.en.md",
        "veafshortcuts — marker aliases": "mission-maker/scripts/veafShortcuts.en.md",
        "veafskynetiadshelper — skynet iads integration": "mission-maker/scripts/veafSkynetIadsHelper.en.md",
        "veafspawn — dynamic unit spawning": "mission-maker/scripts/veafSpawn.en.md",
        "veaftransportmission — transport and logistics missions": "mission-maker/scripts/veafTransportMission.en.md",
        "veafunits — the group database and ground placement": "mission-maker/scripts/veafUnits.en.md",
        "veafweather — dynamic weather and atc conditions": "mission-maker/scripts/veafWeather.en.md",
        "weather variants": "mission-maker/concepts/weather-variants.en.md",
    },
    "fr": {
        "adopter une mission foothold sur la chaîne v6 (la « moulinette": "mission-maker/FOOTHOLD.md",
        "assistant ia d'édition de mission — catalogue des actions": "mission-maker/AI_ASSISTANT_CATALOG.md",
        "convert-other` — adopter une mission tierce sur la v6": "mission-maker/CONVERT_OTHER.md",
        "découvrir vmct en dix minutes": "mission-maker/DISCOVER.md",
        "feuille de route": "ROADMAP.md",
        "groupes spawnables": "mission-maker/concepts/spawnables.md",
        "guide des tests": "TESTING.md",
        "guide du créateur de missions": "mission-maker/README.md",
        "guide du créateur de missions — veaf mission creation tools": "mission-maker/GUIDE.md",
        "guide du développeur": "developer/README.md",
        "guide du développeur — veaf mission creation tools": "developer/GUIDE.md",
        "guide du pilote": "pilot/README.md",
        "guide du pilote — veaf mission creation tools": "pilot/GUIDE.md",
        "générateurs de données de référence dcs": "developer/dcs-data.md",
        "harnais de fumée — vérifier veaf dans un vrai dcs": "developer/smoke-harness.md",
        "installer l'assistant ia de création de missions": "mission-maker/AI_ASSISTANT_INSTALL.md",
        "le build": "mission-maker/concepts/build.md",
        "le dossier de mission": "mission-maker/concepts/mission-folder.md",
        "les fiches — un concept, une page": "mission-maker/concepts/README.md",
        "migration d'une mission vers veaf mct v6": "mission-maker/MIGRATION_GUIDE.md",
        "mission.yaml` et ses modules": "mission-maker/concepts/mission-yaml.md",
        "modules lua veaf — référence api complète": "LUA_API_REFERENCE.md",
        "obtenir de l'aide": "SUPPORT.md",
        "projection des presets radio par type d'aéronef": "developer/radio-preset-projection.md",
        "préréglages radio": "mission-maker/concepts/radio-presets.md",
        "récupérer les aérodromes d'une carte — pas à pas": "developer/capture-airbases.md",
        "référence cli — `veaf-tools": "CLI_REFERENCE.md",
        "référence des alias": "ALIASES.md",
        "référence des scripts — modules lua veaf": "mission-maker/scripts/README.md",
        "référence mission.yaml": "MISSION_YAML_REFERENCE.md",
        "référence pipeline": "PIPELINE_REFERENCE.md",
        "scripts personnalisés": "mission-maker/concepts/custom-scripts.md",
        "slots dynamiques": "mission-maker/concepts/dynamic-slots.md",
        "spécifications des fréquences radio dcs": "mission-maker/dcs-radio-specs.md",
        "tutoriel — votre première mission": "mission-maker/TUTORIAL.md",
        "variantes météo": "mission-maker/concepts/weather-variants.md",
        "veaf mission creation tools — documentation": "index.md",
        "veaf tools — guide utilisateur et administrateur": "TOOLS_REFERENCE.md",
        "veaf-logs — lire les journaux de dcs": "mission-maker/LOGS.md",
        "veaf-mission-mcp` — serveur mcp d'édition de mission assistée par llm": "developer/mission-editing-mcp.md",
        "veaf-tools doctor` — format du bloc collable": "developer/diagnostic-block.md",
        "veaf-tools mission export` — contrat json pour le plugin bfr `dcs-mission-tools": "developer/export-json-contract.md",
        "veafairbases — données de bases aériennes et atc": "mission-maker/scripts/veafAirbases.md",
        "veafairwaves — attaques aériennes par vagues": "mission-maker/scripts/veafAirWaves.md",
        "veafassets — ravitailleurs, awacs et porte-avions": "mission-maker/scripts/veafAssets.md",
        "veafassist — checklists guidées": "mission-maker/scripts/veafAssist.md",
        "veafcarrieroperations — gestion des récupérations sur porte-avions": "mission-maker/scripts/veafCarrierOperations.md",
        "veafcasmission — générateur d'entraînement cas": "mission-maker/scripts/veafCasMission.md",
        "veafcombatmission — le menu missions": "mission-maker/scripts/veafCombatMission.md",
        "veafcombatzone — zones de combat activables": "mission-maker/scripts/veafCombatZone.md",
        "veafcommands — le répartiteur des commandes marqueur": "mission-maker/scripts/veafCommands.md",
        "veafgrass — configuration de pistes en herbe": "mission-maker/scripts/veafGrass.md",
        "veafgroundai — piloter une batterie d'artillerie au marqueur": "mission-maker/scripts/veafGroundAI.md",
        "veafi18n — le catalogue des messages en jeu": "mission-maker/scripts/veafI18n.md",
        "veafinterpreter — commandes embarquées dans les unités": "mission-maker/scripts/veafInterpreter.md",
        "veafmissileguardian — interception de missiles": "mission-maker/scripts/veafMissileGuardian.md",
        "veafmove — déplacement d'unités et gestion des routes de ravitailleurs": "mission-maker/scripts/veafMove.md",
        "veafnamedpoints — points nommés sur la carte": "mission-maker/scripts/veafNamedPoints.md",
        "veafqramanager — alerte de réaction rapide (qra": "mission-maker/scripts/veafQraManager.md",
        "veafradio — gestionnaire du menu radio f10": "mission-maker/scripts/veafRadio.md",
        "veafsanctuary — zones protégées": "mission-maker/scripts/veafSanctuary.md",
        "veafsecurity — permissions par rôle": "mission-maker/scripts/veafSecurity.md",
        "veafserverhook — hook serveur veaf": "mission-maker/scripts/veafServerHook.md",
        "veafshortcuts — aliases de marqueurs": "mission-maker/scripts/veafShortcuts.md",
        "veafskynetiadshelper — intégration skynet iads": "mission-maker/scripts/veafSkynetIadsHelper.md",
        "veafspawn — apparition dynamique d'unités": "mission-maker/scripts/veafSpawn.md",
        "veaftransportmission — missions de transport et logistique": "mission-maker/scripts/veafTransportMission.md",
        "veafunits — la base des groupes et le placement au sol": "mission-maker/scripts/veafUnits.md",
        "veafweather — météo dynamique et conditions atc": "mission-maker/scripts/veafWeather.md",
        "zones de combat": "mission-maker/concepts/combat-zones.md",
    },
}
