"""VMCT-vocabulary edits of a built mission's `veaf-config.lua`, without a rebuild.

These actions know the *semantics* of the VEAF runtime config embedded in the `.miz`
(`l10n/DEFAULT/veaf-config.lua`, generated by the build from `mission.yaml`) and edit the
relevant line: log level, a module's enable flag, the security flag, an arbitrary
`veaf.config.*` value. Each **replaces** the line if present, else **inserts** it near the
top of the config (so it runs before the modules initialise). Backed up first; the rest of
the `.miz` is copied verbatim (no Lua-table re-serialization).
"""

import re
from pathlib import Path
from typing import Any

from mission_tools.miz_backup import backup_before_write
from mission_tools.miz_tools import list_members, read_member, rewrite_miz_members

VEAF_CONFIG_ARCNAME = "l10n/DEFAULT/veaf-config.lua"
_LOG_LEVELS = ("error", "warning", "info", "debug", "trace")


def set_log_level(miz_path: Path, level: str) -> dict[str, Any]:
    """Set the global VEAF log level (`veaf.ForcedLogLevel`) in a built mission.

    Args:
        miz_path: Path to the mission's source `.miz`.
        level: One of ``error``, ``warning``, ``info``, ``debug``, ``trace``.

    Returns:
        `{"line": <new line>, "inserted": <bool>}` (``inserted`` true if the line was
        added, false if an existing one was replaced).

    Raises:
        ValueError: If `level` is unknown or the mission has no `veaf-config.lua`.
    """
    if level not in _LOG_LEVELS:
        raise ValueError(f"Unknown log level: {level!r} (expected one of {_LOG_LEVELS})")
    return _apply(miz_path, r"^veaf\.ForcedLogLevel\s*=.*$", f'veaf.ForcedLogLevel = "{level}"')


def set_module_enabled(miz_path: Path, module_id: str, enabled: bool) -> dict[str, Any]:
    """Enable or disable a VEAF module (`veaf.setConfig("<MOD>", "enable", <bool>)`).

    Args:
        miz_path: Path to the mission's source `.miz`.
        module_id: The module id (e.g. ``"QRA"``, ``"COMBATZONE"``).
        enabled: The new enable state.

    Returns:
        `{"line": <new line>, "inserted": <bool>}`.

    Raises:
        ValueError: If the mission has no `veaf-config.lua`.
    """
    mod = re.escape(module_id)
    pattern = rf'^veaf\.setConfig\("{mod}",\s*"enable",.*$'
    new_line = f'veaf.setConfig("{module_id}", "enable", {_lua_bool(enabled)})'
    return _apply(miz_path, pattern, new_line)


def set_security_disabled(miz_path: Path, disabled: bool) -> dict[str, Any]:
    """Set the VEAF security flag (`veaf.SecurityDisabled`) in a built mission.

    Args:
        miz_path: Path to the mission's source `.miz`.
        disabled: ``True`` = no password required.

    Returns:
        `{"line": <new line>, "inserted": <bool>}`.

    Raises:
        ValueError: If the mission has no `veaf-config.lua`.
    """
    return _apply(miz_path, r"^veaf\.SecurityDisabled\s*=.*$", f"veaf.SecurityDisabled = {_lua_bool(disabled)}")


def set_veaf_config(miz_path: Path, key: str, value: bool | int | float | str) -> dict[str, Any]:
    """Set an arbitrary `veaf.config.<key>` value in a built mission.

    Args:
        miz_path: Path to the mission's source `.miz`.
        key: The config key (the `<key>` in `veaf.config.<key>`).
        value: A scalar (bool/int/float/str) rendered as a Lua literal.

    Returns:
        `{"line": <new line>, "inserted": <bool>}`.

    Raises:
        ValueError: If `key` is not a bare identifier, or the mission has no `veaf-config.lua`.
    """
    if not re.fullmatch(r"[A-Za-z_]\w*", key):
        raise ValueError(f"Invalid veaf.config key: {key!r} (must be a bare Lua identifier)")
    pattern = rf"^veaf\.config\.{re.escape(key)}\s*=.*$"
    return _apply(miz_path, pattern, f"veaf.config.{key} = {_lua_value(value)}")


def _apply(miz_path: Path, line_pattern: str, new_line: str) -> dict[str, Any]:
    """Replace the first line matching `line_pattern` with `new_line`, else insert it on top."""
    if VEAF_CONFIG_ARCNAME not in list_members(miz_path):
        raise ValueError(f"Mission has no {VEAF_CONFIG_ARCNAME} (not a VEAF-built mission?): {miz_path}")
    text = read_member(miz_path, VEAF_CONFIG_ARCNAME).decode("utf-8")
    pattern = re.compile(line_pattern, re.MULTILINE)
    if pattern.search(text):
        new_text = pattern.sub(lambda _m: new_line, text, count=1)
        inserted = False
    else:
        new_text = f"{new_line}\n{text}"
        inserted = True

    backup_before_write(miz_path)
    rewrite_miz_members(miz_path, {VEAF_CONFIG_ARCNAME: new_text.encode("utf-8")})
    return {"line": new_line, "inserted": inserted}


def _lua_bool(value: bool) -> str:
    return "true" if value else "false"


def _lua_value(value: bool | int | float | str) -> str:
    """Render a Python scalar as a Lua literal."""
    if isinstance(value, bool):
        return _lua_bool(value)
    if isinstance(value, (int, float)):
        return str(value)
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
