-- mission-script.lua
-- Generated by veaf-tools convert-v5 (v6.13.96)
--
-- This file should contain ONLY code that cannot be expressed in mission.yaml,
-- such as callback functions for CombatZone, AirWaves, QRA, etc.
-- Module initialization is handled automatically by veaf-config.lua (generated at build time).
--
-- Add your custom code below.

-- ── Callbacks detected during conversion ─────────────────────────────────────
-- The following callbacks were found in missionConfig.lua but cannot be
-- expressed in mission.yaml. Uncomment and implement them here.

-- local function myCallback(arg)
--   -- TODO: implement
-- end
-- veafCombatZone.GetZone("subCombatZone_gori"):setOnCompletedHook(onGoriEnd)

-- local function myCallback(arg)
--   -- TODO: implement
-- end
-- veafAirWaves.get("Zone 01"):setOnDeploy(function ()

-- local function myCallback(arg)
--   -- TODO: implement
-- end
-- veafAirWaves.get("Zone 01"):setHandleCrippledEnemyUnitCallback(handleCrippledEnemyUnit)

-- local function myCallback(arg)
--   -- TODO: implement
-- end
-- veafAirWaves.get("Zone 01"):setIsEnemyGroupDeadCallback(isEnemyGroupDead)
