"""Dynamic loading: dev vs prod framework loader + generated veafDynamicConfig.lua (FIX-DYNLOAD-PUBLISHED)."""

from __future__ import annotations

from pathlib import Path

from mission_builder.mission_builder_worker import CustomScript, MissionBuilderWorker


def _bare_worker() -> MissionBuilderWorker:
    """A worker instance without the heavy __init__ (only the fields the helpers need)."""
    worker = object.__new__(MissionBuilderWorker)
    worker._dcs_bridge_temp_file = None
    worker.custom_scripts = []
    worker.custom_scripts_generate_load_trigger = True
    worker.collected_mission_script_files = None
    worker.config_override_target = None
    worker.config_override_values = {}
    return worker


class TestDynamicFrameworkLoadPath:
    def test_dev_mode_loads_individual_loader(self) -> None:
        worker = _bare_worker()
        worker.dev_mode = True
        assert worker._dynamic_framework_load_path() == "/src/scripts/VeafDynamicLoader.lua"

    def test_prod_mode_loads_bundle(self) -> None:
        worker = _bare_worker()
        worker.dev_mode = False
        assert worker._dynamic_framework_load_path() == "/src/scripts/veaf/veaf-scripts.lua"


class TestGenerateVeafDynamicConfig:
    def test_includes_mission_and_custom_scripts_in_order(self, tmp_path: Path) -> None:
        worker = _bare_worker()
        worker.mission_folder = tmp_path
        worker.custom_scripts = [
            CustomScript(path="FgTools.lua", generate_load_trigger=None),
            CustomScript(path="FgMission.lua", generate_load_trigger=None),
        ]
        # Simulate the collected mission scripts (cache short-circuits the glob).
        worker.collected_mission_script_files = {
            "src/scripts/mission-script.lua": b"",
            "src/scripts/FgTools.lua": b"",
            "src/scripts/FgMission.lua": b"",
        }
        worker.generate_veaf_dynamic_config()

        content = (tmp_path / "src" / "scripts" / "veafDynamicConfig.lua").read_text(encoding="utf-8")
        assert '"mission-script.lua",' in content
        assert '"FgTools.lua",' in content
        assert '"FgMission.lua",' in content
        # Generated marker + ordered iteration (ipairs, not pairs).
        assert "GENERATED by veaf-tools build" in content
        assert "ipairs(scriptsToLoad)" in content
        # Order preserved (FgTools before FgMission).
        assert content.index('"FgTools.lua"') < content.index('"FgMission.lua"')

    def test_does_not_include_itself(self, tmp_path: Path) -> None:
        """veafDynamicConfig.lua is the loader; it must never be in the list it iterates
        (else it would loadfile itself in an infinite loop at mission start)."""
        worker = _bare_worker()
        worker.mission_folder = tmp_path
        worker.custom_scripts = []
        # get_collected_mission_script_files() naturally includes veafDynamicConfig.lua
        # (it is a .lua in src/scripts/); the generated list must filter it out.
        worker.collected_mission_script_files = {
            "src/scripts/veaf-config.lua": b"",
            "src/scripts/mission-script.lua": b"",
            "src/scripts/veafDynamicConfig.lua": b"",
        }
        worker.generate_veaf_dynamic_config()

        content = (tmp_path / "src" / "scripts" / "veafDynamicConfig.lua").read_text(encoding="utf-8")
        assert '"mission-script.lua",' in content
        assert '"veaf-config.lua",' in content
        assert '"veafDynamicConfig.lua",' not in content

    def test_excludes_scripts_with_load_trigger_disabled(self, tmp_path: Path) -> None:
        worker = _bare_worker()
        worker.mission_folder = tmp_path
        worker.custom_scripts = [CustomScript(path="NoTrigger.lua", generate_load_trigger=False)]
        worker.collected_mission_script_files = {
            "src/scripts/mission-script.lua": b"",
            "src/scripts/NoTrigger.lua": b"",
        }
        worker.generate_veaf_dynamic_config()

        content = (tmp_path / "src" / "scripts" / "veafDynamicConfig.lua").read_text(encoding="utf-8")
        assert '"mission-script.lua",' in content
        assert "NoTrigger.lua" not in content
