-- Generated by veaf-tools — do not edit.
-- Hands the mission's CTLD configuration to CTLD 2 and defers its start-up
-- to the VEAF framework (see docs/adr/0016-ctld2-sidecar-configuration.md).
ctld = ctld or {}
ctld.dontInitialize = true
