-- GENERATED by veaf-tools build — do NOT edit by hand.
-- Declare your scripts in mission.yaml (custom_scripts:); this list mirrors
-- the static load triggers so dynamic and static builds load the same files.
-- A `delay` mirrors `delay_seconds:`, which in static mode is a triggerOnce with
-- c_time_after; here it is a scheduled load, so both modes stage alike.
local scriptsToLoad =
{
    { name = "mission-script.lua" },
    { name = "VeafDynamicLoader.lua" },
}

if (VEAF_DYNAMIC_MISSIONPATH) then
    local sMissionScriptsPath = VEAF_DYNAMIC_MISSIONPATH .. [[src\scripts\]]
    for _, script in ipairs(scriptsToLoad) do
        local sPathToExec = sMissionScriptsPath .. script.name
        if script.delay then
            veaf.loggers.get(veaf.Id):info("DynamicConfig: loading " .. sPathToExec .. " in " .. script.delay .. "s")
            timer.scheduleFunction(function()
                veaf.loggers.get(veaf.Id):info("DynamicConfig: loading (delayed) " .. sPathToExec)
                assert(loadfile(sPathToExec))()
            end, {}, timer.getTime() + script.delay)
        else
            veaf.loggers.get(veaf.Id):info("DynamicConfig: loading " .. sPathToExec)
            assert(loadfile(sPathToExec))()
        end
    end
else
        veaf.loggers.get(veaf.Id):error("DynamicConfig: cannot load because the VEAF_DYNAMIC_MISSIONPATH is not set")
end
