"""
Validator that checks radio preset frequencies against DCS aircraft hardware specs.

The specs are loaded from dcs-radio-specs.yaml, which is bundled with the package
and generated by scripts/extract_dcs_radio_specs.py from the dcs-lua-datamine repository.
"""

from __future__ import annotations

import importlib.resources
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from veaf_libs.i18n import t
from veaf_libs.logger import logger

_SPECS: dict[str, Any] | None = None


def _load_specs() -> dict[str, Any]:
    global _SPECS
    if _SPECS is not None:
        return _SPECS

    # When running as a PyInstaller bundle the data file is next to the exe.
    # When running from source it lives in the package data directory.
    bundle_path = Path(getattr(sys, "_MEIPASS", "")) / "presets_injector" / "data" / "dcs-radio-specs.yaml"
    if bundle_path.exists():
        raw = bundle_path.read_text(encoding="utf-8")
    else:
        pkg = importlib.resources.files("presets_injector.data")
        raw = (pkg / "dcs-radio-specs.yaml").read_text(encoding="utf-8")  # type: ignore[arg-type]

    _SPECS = yaml.safe_load(raw) or {}
    return _SPECS


@dataclass(frozen=True)
class FrequencyRange:
    min_mhz: float
    max_mhz: float
    modulation: str

    def contains(self, freq_mhz: float) -> bool:
        return self.min_mhz <= freq_mhz <= self.max_mhz


def get_valid_ranges(unit_type: str) -> list[FrequencyRange] | None:
    """Return the union of all frequency ranges for a given DCS unit type, or None if unknown.

    Args:
        unit_type: DCS unit type string (e.g. "FA-18C_hornet", "MiG-19P").

    Returns:
        List of FrequencyRange covering every valid frequency band across all radios,
        or None if the unit type is not in the specs database.
    """
    specs = _load_specs()
    entry = specs.get(unit_type)
    if not entry:
        return None

    ranges: list[FrequencyRange] = []
    for radio in entry.get("radios", []):
        for r in radio.get("ranges", []):
            ranges.append(
                FrequencyRange(min_mhz=r["min_mhz"], max_mhz=r["max_mhz"], modulation=r.get("modulation", "AM/FM"))
            )
    return ranges


def is_strict(unit_type: str) -> bool:
    """Return True if out-of-range preset frequencies cause DCS to reject the mission at load.

    Most aircraft silently store or ignore frequencies outside their hardware range. A few
    (e.g. MiG-19P, SA342M) raise a hard error when loading the mission. Mark those with
    ``dcs_rejects_on_load: true`` in dcs-radio-specs.yaml.

    Args:
        unit_type: DCS unit type string.

    Returns:
        True if the aircraft is known to crash DCS on invalid preset frequencies.
    """
    specs = _load_specs()
    entry = specs.get(unit_type)
    return bool(entry and entry.get("dcs_rejects_on_load", False))


def validate_frequency(unit_type: str, freq_mhz: float) -> bool | None:
    """Check whether freq_mhz is valid for any radio on the given aircraft.

    Args:
        unit_type: DCS unit type string.
        freq_mhz: Frequency in MHz to validate.

    Returns:
        True if valid, False if invalid, None if the unit type is unknown (no data).
    """
    ranges = get_valid_ranges(unit_type)
    if ranges is None:
        return None
    return any(r.contains(freq_mhz) for r in ranges)


@dataclass
class ChannelFrequency:
    """A frequency with its radio/channel context, used for actionable error messages.

    All name/title fields reflect the presets.yaml structure, not the DCS hardware names.
    """

    freq_mhz: float
    radio_key: str  # key in radios_collection (e.g. "radio_uhf_blue")
    radio_collection: str  # parent collection name (e.g. "blue_radios")
    radio_title: str  # human-readable radio title (e.g. "UHF")
    channel: int  # channel number
    channel_title: str  # channel title/label (e.g. "TACTICAL UNIFORM")


def validate_frequencies(unit_type: str, freqs_mhz: list[float]) -> list[float]:
    """Return the subset of frequencies that are invalid for the given aircraft.

    Args:
        unit_type: DCS unit type string.
        freqs_mhz: List of frequencies in MHz.

    Returns:
        List of invalid frequencies (empty if all are valid or unit type is unknown).
    """
    ranges = get_valid_ranges(unit_type)
    if ranges is None:
        return []
    return [f for f in freqs_mhz if not any(r.contains(f) for r in ranges)]


def _format_ranges(ranges: list[FrequencyRange]) -> str:
    return ", ".join(f"{r.min_mhz}–{r.max_mhz} MHz ({r.modulation})" for r in ranges)


def warn_invalid_channel_frequencies(
    group_names: list[str],
    unit_type: str,
    channels: list[ChannelFrequency],
    coalition: str = "blue",
    aircraft_category: str = "plane",
) -> bool:
    """Log an actionable warning for each channel whose frequency is invalid for unit_type.

    Emits a single warning per aircraft type, listing all affected groups together to avoid
    repeating the same block for every group that uses the same preset.

    Args:
        group_names: Names of the DCS groups using this unit type and preset.
        unit_type: DCS unit type string (e.g. "MiG-19P").
        channels: List of ChannelFrequency carrying radio name, channel number, and frequency.
        coalition: Coalition of the groups ("blue", "red", …).
        aircraft_category: DCS aircraft category ("plane" or "helicopter").
    """
    valid_ranges = get_valid_ranges(unit_type)
    if valid_ranges is None:
        return False

    invalid_channels = [ch for ch in channels if not any(r.contains(ch.freq_mhz) for r in valid_ranges)]
    if not invalid_channels:
        return False

    ranges_str = _format_ranges(valid_ranges)
    if len(group_names) == 1:
        groups_label = t("radio_freq.warn.header_single", group=group_names[0], unit_type=unit_type)
    else:
        groups_str = ", ".join(f"'{g}'" for g in group_names)
        groups_label = t("radio_freq.warn.header_plural", groups=groups_str, unit_type=unit_type)
    # Emit one warning per aircraft type (not per group) to avoid flooding the log.
    # List all invalid channels and all affected groups in a single message.
    channel_lines = "\n".join(
        t(
            "radio_freq.warn.channel_line_titled",
            num=ch.channel,
            title=ch.channel_title,
            freq=ch.freq_mhz,
            collection=ch.radio_collection,
            radio_key=ch.radio_key,
        )
        if ch.channel_title
        else t(
            "radio_freq.warn.channel_line",
            num=ch.channel,
            freq=ch.freq_mhz,
            collection=ch.radio_collection,
            radio_key=ch.radio_key,
        )
        for ch in invalid_channels
    )
    unit_type_key = unit_type.lower().replace(" ", "-")
    footer = t(
        "radio_freq.warn.footer",
        unit_type=unit_type,
        ranges_str=ranges_str,
        coalition=coalition,
        aircraft_category=aircraft_category,
        unit_type_key=unit_type_key,
    )
    message = f"{groups_label}\n{channel_lines}\n{footer}"
    if is_strict(unit_type):
        logger.warning(message)
    else:
        logger.debug(message)
    return True


@dataclass
class FrequencyIssue:
    """A single aircraft type with its invalid channels, suitable for a validation report.

    Attributes:
        unit_type: DCS unit type string.
        group_names: Names of the DCS groups using this unit type.
        invalid_channels: Channels whose frequency falls outside the aircraft's valid ranges.
        valid_ranges: All valid frequency ranges for this aircraft.
        coalition: Coalition of the groups.
        aircraft_category: DCS aircraft category ("plane" or "helicopter").
        strict: True if DCS will reject the mission at load for this aircraft.
    """

    unit_type: str
    group_names: list[str]
    invalid_channels: list[ChannelFrequency]
    valid_ranges: list[FrequencyRange]
    coalition: str
    aircraft_category: str
    strict: bool


def collect_invalid_channel_frequencies(
    group_names: list[str],
    unit_type: str,
    channels: list[ChannelFrequency],
    coalition: str = "blue",
    aircraft_category: str = "plane",
) -> FrequencyIssue | None:
    """Return a FrequencyIssue for channels that are out-of-range for unit_type, or None if all valid.

    Unlike warn_invalid_channel_frequencies, this function does not log anything — it returns
    structured data for use in validation reports.

    Args:
        group_names: Names of the DCS groups using this unit type.
        unit_type: DCS unit type string.
        channels: All channel frequencies to check.
        coalition: Coalition of the groups.
        aircraft_category: DCS aircraft category.

    Returns:
        A FrequencyIssue if any channel is out-of-range, None otherwise (or if unit type unknown).
    """
    valid_ranges = get_valid_ranges(unit_type)
    if valid_ranges is None:
        return None
    invalid_channels = [ch for ch in channels if not any(r.contains(ch.freq_mhz) for r in valid_ranges)]
    if not invalid_channels:
        return None
    return FrequencyIssue(
        unit_type=unit_type,
        group_names=group_names,
        invalid_channels=invalid_channels,
        valid_ranges=valid_ranges,
        coalition=coalition,
        aircraft_category=aircraft_category,
        strict=is_strict(unit_type),
    )


def warn_invalid_frequencies(group_name: str, unit_type: str, freqs_mhz: list[float]) -> None:
    """Log a warning for each frequency in freqs_mhz that is invalid for unit_type.

    Args:
        group_name: Name of the DCS group (for error messages).
        unit_type: DCS unit type string.
        freqs_mhz: Frequencies to check, in MHz.
    """
    valid_ranges = get_valid_ranges(unit_type)
    if valid_ranges is None:
        return
    ranges_str = _format_ranges(valid_ranges)
    for freq in freqs_mhz:
        if not any(r.contains(freq) for r in valid_ranges):
            logger.warning(
                f"Group '{group_name}' ({unit_type}): {freq} MHz is not valid for this aircraft.\n"
                f"  Valid ranges: {ranges_str}\n"
                f"  Fix: in presets.yaml, change this frequency to a value within one of the ranges above."
            )
