"""
Validator that checks radio preset frequencies against DCS aircraft hardware specs.

The specs are loaded from dcs-radio-specs.yaml, which is bundled with the package
and generated by scripts/extract_dcs_radio_specs.py from the dcs-lua-datamine repository.
"""

from __future__ import annotations

import importlib.resources
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from veaf_libs.logger import logger

_SPECS: dict[str, Any] | None = None


def _load_specs() -> dict[str, Any]:
    global _SPECS
    if _SPECS is not None:
        return _SPECS

    # When running as a PyInstaller bundle the data file is next to the exe.
    # When running from source it lives in the package data directory.
    bundle_path = Path(getattr(sys, "_MEIPASS", "")) / "presets_injector" / "data" / "dcs-radio-specs.yaml"
    if bundle_path.exists():
        raw = bundle_path.read_text(encoding="utf-8")
    else:
        pkg = importlib.resources.files("presets_injector.data")
        raw = (pkg / "dcs-radio-specs.yaml").read_text(encoding="utf-8")  # type: ignore[arg-type]

    _SPECS = yaml.safe_load(raw) or {}
    return _SPECS


@dataclass(frozen=True)
class FrequencyRange:
    min_mhz: float
    max_mhz: float
    modulation: str

    def contains(self, freq_mhz: float) -> bool:
        return self.min_mhz <= freq_mhz <= self.max_mhz


def get_valid_ranges(unit_type: str) -> list[FrequencyRange] | None:
    """Return the union of all frequency ranges for a given DCS unit type, or None if unknown.

    Args:
        unit_type: DCS unit type string (e.g. "FA-18C_hornet", "MiG-19P").

    Returns:
        List of FrequencyRange covering every valid frequency band across all radios,
        or None if the unit type is not in the specs database.
    """
    specs = _load_specs()
    entry = specs.get(unit_type)
    if not entry:
        return None

    ranges: list[FrequencyRange] = []
    for radio in entry.get("radios", []):
        for r in radio.get("ranges", []):
            ranges.append(FrequencyRange(min_mhz=r["min_mhz"], max_mhz=r["max_mhz"], modulation=r.get("modulation", "AM/FM")))
    return ranges


def validate_frequency(unit_type: str, freq_mhz: float) -> bool | None:
    """Check whether freq_mhz is valid for any radio on the given aircraft.

    Args:
        unit_type: DCS unit type string.
        freq_mhz: Frequency in MHz to validate.

    Returns:
        True if valid, False if invalid, None if the unit type is unknown (no data).
    """
    ranges = get_valid_ranges(unit_type)
    if ranges is None:
        return None
    return any(r.contains(freq_mhz) for r in ranges)


@dataclass
class ChannelFrequency:
    """A frequency with its radio/channel context, used for actionable error messages."""

    freq_mhz: float
    radio_name: str
    channel: int


def validate_frequencies(unit_type: str, freqs_mhz: list[float]) -> list[float]:
    """Return the subset of frequencies that are invalid for the given aircraft.

    Args:
        unit_type: DCS unit type string.
        freqs_mhz: List of frequencies in MHz.

    Returns:
        List of invalid frequencies (empty if all are valid or unit type is unknown).
    """
    ranges = get_valid_ranges(unit_type)
    if ranges is None:
        return []
    return [f for f in freqs_mhz if not any(r.contains(f) for r in ranges)]


def _format_ranges(ranges: list[FrequencyRange]) -> str:
    return ", ".join(f"{r.min_mhz}–{r.max_mhz} MHz ({r.modulation})" for r in ranges)


def warn_invalid_channel_frequencies(
    group_name: str,
    unit_type: str,
    channels: list[ChannelFrequency],
) -> None:
    """Log an actionable warning for each channel whose frequency is invalid for unit_type.

    Args:
        group_name: Name of the DCS group.
        unit_type: DCS unit type string.
        channels: List of ChannelFrequency carrying radio name, channel number, and frequency.
    """
    valid_ranges = get_valid_ranges(unit_type)
    if valid_ranges is None:
        return

    ranges_str = _format_ranges(valid_ranges)
    for ch in channels:
        if not any(r.contains(ch.freq_mhz) for r in valid_ranges):
            logger.warning(
                f"Group '{group_name}' ({unit_type}): radio '{ch.radio_name}', channel {ch.channel} "
                f"— {ch.freq_mhz} MHz is not valid for this aircraft.\n"
                f"  Valid ranges: {ranges_str}\n"
                f"  Fix: in presets.yaml, change the frequency for radio '{ch.radio_name}' "
                f"channel {ch.channel} to a value within one of the ranges above."
            )


def warn_invalid_frequencies(group_name: str, unit_type: str, freqs_mhz: list[float]) -> None:
    """Log a warning for each frequency in freqs_mhz that is invalid for unit_type.

    Args:
        group_name: Name of the DCS group (for error messages).
        unit_type: DCS unit type string.
        freqs_mhz: Frequencies to check, in MHz.
    """
    valid_ranges = get_valid_ranges(unit_type)
    if valid_ranges is None:
        return
    ranges_str = _format_ranges(valid_ranges)
    for freq in freqs_mhz:
        if not any(r.contains(freq) for r in valid_ranges):
            logger.warning(
                f"Group '{group_name}' ({unit_type}): {freq} MHz is not valid for this aircraft.\n"
                f"  Valid ranges: {ranges_str}\n"
                f"  Fix: in presets.yaml, change this frequency to a value within one of the ranges above."
            )
