"""Generate the airfield ATC-frequency table, and the default channel collections, from DCS itself.

**Where the frequencies really are.** The Mission Editor builds each airfield's frequency list in
``MissionEditor/modules/Mission/AirdromeData.lua``: the airdrome's ``frequency`` field from the terrain
configuration (``Terrain.GetTerrainConfig('Airdromes')``) when there is one, else
``DCS.getATCradiosData(radioId)`` for each of its radio ids. Measured 2026-10-01 on all seven installed
theatres: no airdrome has a ``frequency`` field, so every list comes from ``DCS.getATCradiosData`` — and
that function returns bands **the text of** ``Radio.lua`` **does not hold**. Persian Gulf's ``radio.lua``
gives Al Dhafra 126.5 VHF only; DCS returns 39.5 / 126.5 / 251.1 / 4.3, what the editor's airport panel
shows. Bandar-e-Jask has ``frequency = {}`` in the file and four bands in DCS. Where DCS completes them is
not visible from the install. The earlier generator, which parsed ``Radio.lua``'s text, was therefore
wrong; it also keyed airfields by radio callsign (``OMAA``) and lost those sharing one.

So the pipeline has two steps:

1. **Capture**, once per theatre, from a running DCS through the fiddle hook's GUI environment
   (:data:`CAPTURE_LUA`, the editor's own logic), guided by :mod:`airfield_freqs_session`. The TACAN
   channels are read at the same moment from the install's ``Beacons.lua``
   (``beaconId = 'airfield<id>_<n>'``) and folded into the dump. Dumps are committed as
   ``airfield_freq_dumps/<Theatre>.json``, one per theatre, so a machine missing a map never touches
   that map's data.
2. **Generate**, offline and reproducibly, from the committed dumps: the reference
   ``veaf_libs/data/airfield-frequencies.yaml`` (keyed by DCS airdrome id, the key a mission's
   ``warehouses`` uses) and the ``airports-<theatre>`` collections of the default ``presets.yaml``,
   rewritten between :data:`BLOCK_START` and :data:`BLOCK_END` only.

Run via ``veaf-build update-dcs-data --airfield-freqs --capture --dcs-path <DCS>`` (with a mission on
the map running) then ``veaf-build update-dcs-data --airfield-freqs``.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import yaml
from presets_injector.airfield_channels_manager import channel_title, yaml_scalar  # type: ignore[import-not-found]
from veaf_libs.lua_literals import lua_comment_line, lua_quoted_string  # type: ignore[import-not-found]

from veaf_build.dcs_data.airdromes import LEGACY_THEATRE_ALIASES

_ROOT = Path(__file__).parent.parent.parent

#: Committed reference consumed at design time (convert-v5 aliasing, the mission airfield plan).
DEFAULT_OUTPUT = _ROOT / "src/python/veaf-tools/veaf_libs/data/airfield-frequencies.yaml"

#: The same reference rendered for the mission scripts, which cannot ask DCS for it (FEAT-AIRFIELD-FREQS-IN-ATIS).
DEFAULT_LUA = _ROOT / "src/scripts/veaf/veafAirfieldFrequencies.lua"

#: The shipped default plan, whose ``airports-<theatre>`` collections are generated.
DEFAULT_PRESETS = _ROOT / "src/defaults/mission-folder/src/presets.yaml"

#: Committed captures, one ``<Theatre>.json`` per theatre.
DUMPS_DIR = Path(__file__).parent / "airfield_freq_dumps"

#: The runtime airbase dumps, whose ``Airbase:getName()`` is the name a mission uses.
AIRBASE_DUMPS_DIR = Path(__file__).parent / "airbase_dumps"

#: Markers around the generated collections in :data:`DEFAULT_PRESETS`.
BLOCK_START = "    # >>> airfield channels — generated by `veaf-build update-dcs-data --airfield-freqs`, do not edit"
BLOCK_END = "    # <<< airfield channels"

#: Runtime theatre name (``env.mission.theatre``) -> install folder under ``Mods/terrains``, where the
#: two differ: ``airdromes.LEGACY_THEATRE_ALIASES`` read the other way round, not a copy of it.
_TERRAIN_FOLDERS: dict[str, str] = {runtime: folder for folder, runtime in LEGACY_THEATRE_ALIASES.items()}

#: Collection names kept stable for the three theatres that already had one.
_COLLECTION_NAMES: dict[str, str] = {
    "Caucasus": "airports-caucasus",
    "Syria": "airports-syria",
    "PersianGulf": "airports-persian-gulf",
    "GermanyCW": "airports-germany-cold-war",
    "SinaiMap": "airports-sinai",
}

#: Runs in the fiddle hook's own (GUI) environment, where ``require('terrain')`` and ``DCS`` live.
#: It is ``me_terrainDATA.updateDATA`` + ``AirdromeData.onNewMission`` reduced to what we keep: same
#: filter (a reference point, not abandoned), same precedence (``frequency``, else the radio ids).
CAPTURE_LUA = r"""
local okT, T = pcall(require, 'terrain')
if not okT or not T then T = Terrain end
if not T or not T.GetTerrainConfig then return {error = 'terrain module unavailable in this environment'} end
local theatre = T.GetTerrainConfig('id')
local okM, mission = pcall(function() return DCS.getCurrentMission() end)
if okM and mission and mission.mission and mission.mission.theatre then theatre = mission.mission.theatre end
local airdromes = T.GetTerrainConfig('Airdromes')
if not airdromes then return {error = 'no Airdromes in the terrain configuration (is a mission running?)'} end
local out = {}
for id, info in pairs(airdromes) do
  if info.reference_point and info.abandoned ~= true then
    local freqs, source = {}, 'none'
    if info.frequency then
      source = 'terrain'
      for _, f in ipairs(info.frequency) do freqs[#freqs + 1] = {f[1], f[2]} end
    elseif info.radio and DCS.getATCradiosData then
      source = 'radio'
      for _, radioId in pairs(info.radio) do
        local list = DCS.getATCradiosData(radioId)
        if list then for _, f in pairs(list) do freqs[#freqs + 1] = {f[1], f[2]} end end
      end
    end
    local name = info.display_name or (info.names and info.names.en) or tostring(id)
    out[#out + 1] = {id = id, name = name, source = source, freqs = freqs}
  end
end
return {theatre = theatre, airdromes = out}
"""

# From an airfield beacon's id to the next beacon's: holds its type and channel. An entry nests
# `position = { ... }`, so it cannot be cut on braces.
_BEACON_RE = re.compile(r"beaconId\s*=\s*'airfield(\d+)_\d+'(.*?)(?=beaconId|\Z)", re.DOTALL)
_CHANNEL_RE = re.compile(r"channel\s*=\s*(\d+)")


def band_of(mhz: float) -> str | None:
    """Return the VEAF band of an ATC frequency.

    Args:
        mhz: Frequency in MHz.

    Returns:
        ``hf``, ``fm`` (VHF low), ``vhf`` (VHF high) or ``uhf``; ``None`` outside the aircraft bands.
    """
    if mhz < 30:
        return "hf"
    if mhz < 88:
        return "fm"
    if 108 <= mhz < 174:
        return "vhf"
    if 225 <= mhz <= 400:
        return "uhf"
    return None


def parse_tacans(text: str) -> dict[int, str]:
    """Read the airfield TACAN channels of a terrain ``Beacons.lua``.

    A VORTAC counts: it carries a TACAN channel, and is how Persian Gulf declares Al Dhafra (96X) and
    Liwa (121X). DCS ground TACANs answer in X mode, which is also how every hand-written VEAF title
    spells them.

    Args:
        text: Raw contents of ``Beacons.lua``.

    Returns:
        Airdrome id -> ``"<channel>X"`` (first TACAN per airfield).
    """
    tacans: dict[int, str] = {}
    for airdrome_id, body in _BEACON_RE.findall(text):
        if "BEACON_TYPE_TACAN" not in body and "BEACON_TYPE_VORTAC" not in body:
            continue
        channel = _CHANNEL_RE.search(body)
        if channel:
            tacans.setdefault(int(airdrome_id), f"{int(channel.group(1))}X")
    return dict(sorted(tacans.items()))


def parse_capture(result: Any) -> tuple[str, list[dict[str, Any]]]:
    """Validate what :data:`CAPTURE_LUA` returned and convert its frequencies to MHz.

    Args:
        result: The hook's result: a dict, or the same as a JSON string.

    Returns:
        The theatre name and one ``{id, name, source, freqs: [MHz…]}`` record per airdrome.

    Raises:
        ValueError: The result is a Lua error, an ``{error}`` report, or carries no airdrome.
    """
    if isinstance(result, str):
        try:
            result = json.loads(result)
        except json.JSONDecodeError as exc:
            raise ValueError(f"the capture did not run: {result[:300]}") from exc
    if not isinstance(result, dict):
        raise ValueError(f"unexpected capture result: {result!r:.300}")
    if "error" in result:
        raise ValueError(f"the capture failed in DCS: {result['error']}")
    theatre = result.get("theatre")
    airdromes = result.get("airdromes") or []
    if not theatre or not airdromes:
        raise ValueError(f"the capture returned no theatre or no airdrome: {result!r:.300}")
    records = [
        {
            "id": int(a["id"]),
            "name": str(a["name"]),
            "source": str(a.get("source", "")),
            "freqs": [round(float(f[0]) / 1_000_000, 4) for f in a.get("freqs") or []],
        }
        for a in airdromes
    ]
    return str(theatre), records


def terrain_folder(theatre: str) -> str:
    """Return the ``Mods/terrains`` folder of a runtime theatre name.

    Args:
        theatre: ``env.mission.theatre`` value.

    Returns:
        The install folder name.
    """
    return _TERRAIN_FOLDERS.get(theatre, theatre)


def write_dump(theatre: str, records: list[dict[str, Any]], tacans: dict[int, str], dumps_dir: Path) -> Path:
    """Write one theatre's capture, TACAN folded in, as ``<theatre>.json``.

    Args:
        theatre: Runtime theatre name.
        records: Output of :func:`parse_capture`.
        tacans: Output of :func:`parse_tacans` for that theatre.
        dumps_dir: Destination directory.

    Returns:
        The written path.
    """
    airdromes = []
    for record in sorted(records, key=lambda r: r["id"]):
        entry = dict(record)
        if record["id"] in tacans:
            entry["tacan"] = tacans[record["id"]]
        airdromes.append(entry)
    dumps_dir.mkdir(parents=True, exist_ok=True)
    path = dumps_dir / f"{theatre}.json"
    path.write_text(
        json.dumps({"theatre": theatre, "airdromes": airdromes}, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return path


def load_dumps(dumps_dir: Path = DUMPS_DIR) -> dict[str, list[dict[str, Any]]]:
    """Read every committed capture.

    Args:
        dumps_dir: Directory of ``<Theatre>.json`` captures.

    Returns:
        Theatre -> airdrome records.
    """
    dumps: dict[str, list[dict[str, Any]]] = {}
    for path in sorted(dumps_dir.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        dumps[data["theatre"]] = data["airdromes"]
    return dumps


def load_airbase_names(airbase_dumps_dir: Path = AIRBASE_DUMPS_DIR) -> dict[str, dict[int, str]]:
    """Read the runtime airbase names (``Airbase:getName()``) by theatre and id.

    Args:
        airbase_dumps_dir: Directory of the ``capture-map`` airbase dumps.

    Returns:
        Theatre -> airdrome id -> name.
    """
    names: dict[str, dict[int, str]] = {}
    for path in sorted(airbase_dumps_dir.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        names[data["theatre"]] = {int(a["id"]): str(a["name"]) for a in data["airbases"] if "id" in a}
    return names


def reference_from_dumps(
    dumps: dict[str, list[dict[str, Any]]], airbase_names: dict[str, dict[int, str]]
) -> dict[str, dict[int, dict[str, Any]]]:
    """Derive the reference: per theatre and airdrome id, a name and one frequency per band.

    The first frequency of each band wins, in the order DCS lists them. HF is dropped (no VEAF plan uses
    it), and an airdrome with no frequency in any kept band is left out — it cannot carry a channel.

    Args:
        dumps: Output of :func:`load_dumps`.
        airbase_names: Output of :func:`load_airbase_names`; the terrain's own name is the fallback.

    Returns:
        Theatre -> id -> ``{name, uhf?, vhf?, fm?, tacan?}``, sorted.
    """
    reference: dict[str, dict[int, dict[str, Any]]] = {}
    for theatre in sorted(dumps):
        names = airbase_names.get(theatre, {})
        entries: dict[int, dict[str, Any]] = {}
        for record in sorted(dumps[theatre], key=lambda r: int(r["id"])):
            airdrome_id = int(record["id"])
            entry: dict[str, Any] = {"name": names.get(airdrome_id, record["name"])}
            for mhz in record.get("freqs") or []:
                band = band_of(mhz)
                if band in ("uhf", "vhf", "fm"):
                    entry.setdefault(band, mhz)
            if len(entry) == 1:
                continue
            if record.get("tacan"):
                entry["tacan"] = record["tacan"]
            entries[airdrome_id] = entry
        reference[theatre] = entries
    return reference


def collection_name(theatre: str) -> str:
    """Return the ``channels_collection`` name of a theatre's airfields.

    Args:
        theatre: Runtime theatre name.

    Returns:
        ``airports-<kebab-case theatre>``, or the historical name where one exists.
    """
    if theatre in _COLLECTION_NAMES:
        return _COLLECTION_NAMES[theatre]
    return "airports-" + re.sub(r"(?<!^)(?=[A-Z])", "-", theatre).lower()


def collections_from_reference(
    reference: dict[str, dict[int, dict[str, Any]]],
) -> dict[str, dict[str, dict[str, Any]]]:
    """Turn the reference into one channel collection per theatre, aliased by airfield name.

    An alias is unique across **all** collections: the build resolves an alias in the first
    collection holding it, whatever the mission's theatre. Eight fields exist on both Sinai and Syria
    with different frequencies (Hatzor: 250.6 on one, 250.75 on the other), so a name found on more
    than one theatre is aliased ``<name> (<theatre>)`` — a bare ``Hatzor`` then fails the build
    instead of silently taking the other map's tower. Two fields sharing a name **within** a theatre
    (none today; the callsign data had two ``LeMolay`` on Normandy) are aliased ``<name> [<id>]``
    rather than one of them being dropped.

    Args:
        reference: Output of :func:`reference_from_dumps`.

    Returns:
        Collection name -> alias -> ``{title, freqs}``, theatres and aliases sorted.
    """
    theatres_of: dict[str, int] = {}
    for entries in reference.values():
        for name in {e["name"] for e in entries.values()}:
            theatres_of[name] = theatres_of.get(name, 0) + 1
    collections: dict[str, dict[str, dict[str, Any]]] = {}
    for theatre in sorted(reference):
        channels: dict[str, dict[str, Any]] = {}
        in_theatre: dict[str, int] = {}
        for entry in reference[theatre].values():
            in_theatre[entry["name"]] = in_theatre.get(entry["name"], 0) + 1
        for airdrome_id, entry in sorted(reference[theatre].items(), key=lambda item: (item[1]["name"], item[0])):
            freqs = {band: entry[band] for band in ("uhf", "vhf", "fm") if band in entry}
            alias = f"{entry['name']} ({theatre})" if theatres_of[entry["name"]] > 1 else entry["name"]
            if in_theatre[entry["name"]] > 1:
                alias = f"{alias} [{airdrome_id}]"
            channels[alias] = {"title": channel_title(entry["name"], entry.get("tacan")), "freqs": freqs}
        collections[collection_name(theatre)] = channels
    return collections


def render_collections(collections: dict[str, dict[str, dict[str, Any]]]) -> str:
    """Render collections as YAML indented to sit under ``channels_collection:``.

    Args:
        collections: Output of :func:`collections_from_reference`.

    Returns:
        The YAML text, four spaces deep.
    """
    lines: list[str] = []
    for name, channels in collections.items():
        lines.append(f"    {name}:")
        for alias, channel in channels.items():
            freqs = ", ".join(f"{band}: {value}" for band, value in channel["freqs"].items())
            lines.append(f"      {yaml_scalar(alias)}:")
            lines.append(f"        title: {yaml_scalar(channel['title'])}")
            lines.append(f"        freqs: {{ {freqs} }}")
    return "\n".join(lines) + "\n"


def replace_generated_block(text: str, block: str) -> str:
    """Swap what sits between :data:`BLOCK_START` and :data:`BLOCK_END`, nothing else.

    Args:
        text: The whole ``presets.yaml``.
        block: The new content, newline-terminated.

    Returns:
        The updated text.

    Raises:
        ValueError: If either marker is missing.
    """
    start = re.search(r"^ *# >>> airfield channels.*\n", text, re.MULTILINE)
    end = re.search(r"^ *# <<< airfield channels.*$", text, re.MULTILINE)
    if not start or not end or end.start() < start.end():
        raise ValueError("the airfield-channel markers are missing from presets.yaml")
    return text[: start.end()] + block + text[end.start() :]


_LUA_HEADER = """------------------------------------------------------------------
-- VEAF airfield frequencies: the tower frequencies (MHz) and TACAN DCS gives each airfield, per
-- theatre (env.mission.theatre) and DCS airdrome id (Airbase:getID()). Read by veafAirbases for the
-- welcome brief and the ATIS: the mission scripts have no API to ask DCS for them.
--
-- GENERATED from veaf_libs/data/airfield-frequencies.yaml by `veaf-build update-dcs-data --airfield-freqs`.
-- DO NOT EDIT BY HAND — edits are overwritten and a test fails on drift.
------------------------------------------------------------------

veafAirfieldFrequencies = {}
"""


def load_reference(path: Path) -> dict[str, dict[int, dict[str, Any]]]:
    """Read a committed reference YAML back.

    Args:
        path: The reference written by :func:`write_reference`.

    Returns:
        Theatre -> airdrome id -> ``{name, uhf?, vhf?, fm?, tacan?}``.
    """
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {
        theatre: {int(airdrome_id): entry for airdrome_id, entry in (entries or {}).items()}
        for theatre, entries in (data.get("theatres") or {}).items()
    }


def render_lua(reference: dict[str, dict[int, dict[str, Any]]]) -> str:
    """Render ``veafAirfieldFrequencies.lua``: theatre -> airdrome id -> ``{uhf, vhf, fm, tacan}``.

    Frequencies are written as Python's shortest round-trip form, so ``126.525`` stays ``126.525``; a
    band the field does not have is left out rather than written as ``nil``. The airfield's name is a
    trailing comment, for whoever reads the file.

    Args:
        reference: Output of :func:`reference_from_dumps` (or :func:`load_reference`).

    Returns:
        The complete Lua source.
    """
    lines = [_LUA_HEADER]
    for theatre, entries in sorted(reference.items()):
        lines.append(f"veafAirfieldFrequencies[{lua_quoted_string(theatre)}] = {{")
        for airdrome_id, entry in sorted(entries.items()):
            fields = [f"{band} = {float(entry[band])!r}" for band in ("uhf", "vhf", "fm") if band in entry]
            if entry.get("tacan"):
                fields.append(f"tacan = {lua_quoted_string(str(entry['tacan']))}")
            lines.append(lua_comment_line(f"  [{int(airdrome_id)}] = {{ {', '.join(fields)} }}, -- {entry['name']}"))
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def write_reference(reference: dict[str, dict[int, dict[str, Any]]], output: Path) -> None:
    """Write the committed reference YAML.

    Args:
        reference: Output of :func:`reference_from_dumps`.
        output: Destination path.
    """
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w", encoding="utf-8", newline="\n") as f:
        f.write("# DCS airfield ATC frequencies (MHz), per theatre and DCS airdrome id.\n")
        f.write("# Captured from a running DCS with the Mission Editor's own logic (DCS completes bands the\n")
        f.write("# text of Radio.lua does not hold), TACAN from Beacons.lua. Do not edit: regenerate with\n")
        f.write("# `veaf-build update-dcs-data --airfield-freqs` from veaf_build/dcs_data/airfield_freq_dumps/.\n")
        f.write("# Bands: uhf, vhf (VHF high), fm (VHF low); HF dropped. Names are Airbase:getName().\n\n")
        yaml.safe_dump({"theatres": reference}, f, allow_unicode=True, sort_keys=False, default_flow_style=False)


def generate(
    output: Path = DEFAULT_OUTPUT,
    presets: Path = DEFAULT_PRESETS,
    dumps_dir: Path = DUMPS_DIR,
    airbase_dumps_dir: Path = AIRBASE_DUMPS_DIR,
    lua_output: Path = DEFAULT_LUA,
) -> int:
    """Regenerate the reference, its Lua rendering and the default airfield collections from the captures.

    Args:
        output: Reference YAML path.
        presets: Default ``presets.yaml`` holding the generated block.
        dumps_dir: Directory of the captures.
        airbase_dumps_dir: Directory of the runtime airbase dumps (names).
        lua_output: The Lua table the mission scripts load.

    Returns:
        The number of airfields written across all theatres.

    Raises:
        FileNotFoundError: No capture is committed — generating would erase every theatre.
    """
    dumps = load_dumps(dumps_dir)
    if not dumps:
        raise FileNotFoundError(f"no airfield-frequency capture in {dumps_dir}")
    reference = reference_from_dumps(dumps, load_airbase_names(airbase_dumps_dir))
    write_reference(reference, output)
    lua_output.parent.mkdir(parents=True, exist_ok=True)
    with open(lua_output, "w", encoding="utf-8", newline="\n") as f:
        f.write(render_lua(load_reference(output)))
    text = presets.read_text(encoding="utf-8")
    updated = replace_generated_block(text, render_collections(collections_from_reference(reference)))
    if updated != text:
        presets.write_text(updated, encoding="utf-8", newline="\n")
    return sum(len(entries) for entries in reference.values())
