"""Partial config-override rendering and lexical validation (FOOTHOLD-V6-004).

A third-party mission like Foothold ships a large, author-controlled config file
that VEAF leaves untouched. A *partial override* (``config_override:`` in
``mission.yaml``) restates only the handful of globals a mission-maker changes at
deploy time. This module renders that mapping to a small Lua script — loaded
between the upstream config and the setup script — and validates each key
lexically against the injected Foothold corpus. See ADR 0008.

Validation is **lexical, not syntactic**: each dotted-path segment is searched as
an identifier (``\\bsegment\\b``) across the whole corpus. A segment found nowhere
is a typo, rename, or upstream removal and must fail the build. Pure-Python regex,
**no Lua execution** (per SECREV-001 — ``lupa`` must not be reintroduced).
"""

from __future__ import annotations

import re
from pathlib import Path

#: Filename of the Lua script the build renders from ``config_override:``.
#: It carries no "foothold" knowledge — the override mechanism is generic.
OVERRIDE_SCRIPT_NAME = "veaf-config-override.lua"

#: Lua source file extension scanned when building the validation corpus.
_LUA_SUFFIX = ".lua"


def _to_lua_value(value: object) -> str:
    """Render a Python scalar as a Lua literal.

    Booleans become ``true``/``false``, numbers are emitted verbatim, ``None``
    becomes ``nil``, and strings are double-quoted — falling back to a Lua
    long-string (``[[...]]`` with a safe bracket level) when the text contains a
    newline, double-quote, or backslash that a plain literal could not carry.

    Args:
        value: The Python value to render.

    Returns:
        A valid Lua literal for *value*.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if value is None:
        return "nil"
    text = str(value)
    if "\n" in text or '"' in text or "\\" in text:
        level = 0
        while f"]{'=' * level}]" in text:
            level += 1
        eq = "=" * level
        return f"[{eq}[{text}]{eq}]"
    return f'"{text}"'


def render_override_lua(values: dict[str, object]) -> str:
    """Render the override Lua script that reassigns the changed globals.

    Each entry ``key: value`` becomes a ``key = <lua value>`` assignment, where
    *key* may be a dotted Lua path (e.g. ``"Config.SubTable.Field"``). Key order
    is preserved so the output is deterministic.

    Args:
        values: Mapping of dotted Lua-global paths to scalar values.

    Returns:
        The complete Lua source, ready to write to :data:`OVERRIDE_SCRIPT_NAME`.
    """
    lines = [
        "-- GENERATED by veaf-tools build — do NOT edit by hand.",
        "-- Partial config override (mission.yaml: config_override:). Reassigns only",
        "-- the changed globals, loaded between the upstream config and the setup script.",
        "",
    ]
    for key, value in values.items():
        lines.append(f"{key} = {_to_lua_value(value)}")
    return "\n".join(lines) + "\n"


def find_unknown_segments(values: dict[str, object], corpus: str) -> list[str]:
    """Return the override key segments absent from *corpus*, in first-seen order.

    Each key is split on ``.`` and every segment is searched as a whole-word
    identifier (``\\bsegment\\b``) in *corpus*. A non-empty result means the
    override references an identifier that exists nowhere in the injected code —
    a typo or an upstream rename — which the caller turns into a build-blocking
    error. Segments are de-duplicated while preserving order.

    Args:
        values: The ``config_override.values`` mapping.
        corpus: The concatenated Lua source to validate against.

    Returns:
        The unknown segments (empty when every segment is found).
    """
    unknown: list[str] = []
    seen: set[str] = set()
    for key in values:
        for raw_segment in str(key).split("."):
            segment = raw_segment.strip()
            if not segment or segment in seen:
                continue
            seen.add(segment)
            if not re.search(rf"\b{re.escape(segment)}\b", corpus):
                unknown.append(segment)
    return unknown


def read_corpus(scripts_dir: Path) -> str:
    """Concatenate the Lua sources that form the lexical-validation corpus.

    Every ``*.lua`` file directly under *scripts_dir* is included **except** the
    generated override script itself (so it never validates against its own
    assignments). Files are read in sorted order for determinism; unreadable
    files are skipped.

    Args:
        scripts_dir: The mission's ``src/scripts`` directory.

    Returns:
        The concatenated source, or ``""`` when the directory is absent or empty.
    """
    if not scripts_dir.is_dir():
        return ""
    parts: list[str] = []
    for lua_file in sorted(scripts_dir.glob(f"*{_LUA_SUFFIX}")):
        if lua_file.name == OVERRIDE_SCRIPT_NAME:
            continue
        try:
            parts.append(lua_file.read_text(encoding="utf-8", errors="ignore"))
        except OSError:
            continue
    return "\n".join(parts)
