"""VEAF Lua module scanner.

Provides a list of VEAF Lua modules (id, version, filename) from three
sources, tried in order:

1. A JSON file bundled inside a PyInstaller executable (``sys._MEIPASS``).
2. A pre-generated ``veaf_modules_list.json`` sitting next to this module
   (generated by ``build-and-release.py`` before compilation).
3. A live scan of ``src/scripts/veaf/veaf*.lua`` (development mode — walks
   up the directory tree from this file to locate the repo root).

Use :func:`generate_modules_json` from ``build-and-release.py`` to produce
the JSON file that is then bundled with PyInstaller.
"""

import json
import re
import sys
from pathlib import Path
from typing import TypedDict

_BUNDLED_JSON_NAME = "veaf_modules_list.json"
_LUA_SCRIPTS_SUBPATH = Path("src") / "scripts" / "veaf"


class LuaModule(TypedDict):
    id: str
    version: str
    filename: str


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _bundled_json_path() -> Path | None:
    """Return the path to the JSON bundled inside a PyInstaller exe, or None."""
    if hasattr(sys, "_MEIPASS"):
        candidate = Path(sys._MEIPASS) / _BUNDLED_JSON_NAME  # type: ignore[attr-defined]
        if candidate.exists():
            return candidate
    return None


def _pregenerated_json_path() -> Path | None:
    """Return the path to a pre-generated JSON next to this module, or None."""
    candidate = Path(__file__).parent / _BUNDLED_JSON_NAME
    return candidate if candidate.exists() else None


def _find_lua_scripts_dir() -> Path | None:
    """Walk up the directory tree to locate ``src/scripts/veaf``."""
    candidate = Path(__file__).parent
    for _ in range(12):
        lua_dir = candidate / _LUA_SCRIPTS_SUBPATH
        if lua_dir.is_dir():
            return lua_dir
        candidate = candidate.parent
    return None


def _scan_lua_directory(lua_dir: Path) -> list[LuaModule]:
    """Scan *lua_dir* for ``veaf*.lua`` files and extract id / version."""
    id_re = re.compile(r'\bveaf\w+\.Id\s*=\s*"([^"]+)"')
    ver_re = re.compile(r'\bveaf\w+\.Version\s*=\s*"([^"]+)"')
    modules: list[LuaModule] = []

    for lua_file in sorted(lua_dir.glob("veaf*.lua")):
        try:
            content = lua_file.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        id_match = id_re.search(content)
        ver_match = ver_re.search(content)
        if id_match:
            modules.append(
                LuaModule(
                    id=id_match.group(1),
                    version=ver_match.group(1) if ver_match else "",
                    filename=lua_file.name,
                )
            )
    return modules


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_modules() -> list[LuaModule]:
    """Return the list of VEAF Lua modules.

    Sources tried in order:
    1. Bundled JSON (PyInstaller bundle at ``sys._MEIPASS``).
    2. Pre-generated JSON next to this module.
    3. Live scan of ``src/scripts/veaf/`` (repo checkout).
    """
    # 1. PyInstaller bundle
    path = _bundled_json_path()
    if path:
        return json.loads(path.read_text(encoding="utf-8"))

    # 2. Pre-generated JSON
    path = _pregenerated_json_path()
    if path:
        return json.loads(path.read_text(encoding="utf-8"))

    # 3. Live scan
    lua_dir = _find_lua_scripts_dir()
    if lua_dir:
        return _scan_lua_directory(lua_dir)

    return []


def generate_modules_json(output_path: Path, lua_dir: Path) -> int:
    """Scan *lua_dir* and write the modules list to *output_path* as JSON.

    Called by ``build-and-release.py`` before the PyInstaller compilation
    step so the resulting JSON can be bundled with ``--add-data``.

    Returns:
        Number of modules written.
    """
    modules = _scan_lua_directory(lua_dir)
    output_path.write_text(json.dumps(modules, indent=2, ensure_ascii=False), encoding="utf-8")
    return len(modules)
