"""VEAF Lua module scanner.

Provides a list of VEAF Lua modules (id, version, filename) from three
sources, tried in order:

1. A JSON file bundled inside a PyInstaller executable (``sys._MEIPASS``).
2. A pre-generated ``veaf_modules_list.json`` sitting next to this module
   (generated by ``build-and-release.py`` before compilation).
3. A live scan of ``src/scripts/veaf/veaf*.lua`` (development mode — walks
   up the directory tree from this file to locate the repo root).

Use :func:`generate_modules_json` from ``build-and-release.py`` to produce
the JSON file that is then bundled with PyInstaller.
"""

import json
import re
import sys
from pathlib import Path
from typing import TypedDict

from veaf_libs.i18n import t

_BUNDLED_JSON_NAME = "veaf_modules_list.json"
_LUA_SCRIPTS_SUBPATH = Path("src") / "scripts" / "veaf"


class LuaModule(TypedDict):
    id: str
    version: str
    filename: str
    var_name: str  # variable prefix from the .Id line (may differ from filename stem)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _bundled_json_path() -> Path | None:
    """Return the path to the JSON bundled inside a PyInstaller exe, or None."""
    if hasattr(sys, "_MEIPASS"):
        candidate = Path(sys._MEIPASS) / _BUNDLED_JSON_NAME  # type: ignore[attr-defined]
        if candidate.exists():
            return candidate
    return None


def _pregenerated_json_path() -> Path | None:
    """Return the path to a pre-generated JSON next to this module, or None."""
    candidate = Path(__file__).parent / _BUNDLED_JSON_NAME
    return candidate if candidate.exists() else None


def _find_lua_scripts_dir() -> Path | None:
    """Walk up the directory tree to locate ``src/scripts/veaf``."""
    candidate = Path(__file__).parent
    for _ in range(12):
        lua_dir = candidate / _LUA_SCRIPTS_SUBPATH
        if lua_dir.is_dir():
            return lua_dir
        candidate = candidate.parent
    return None


def _scan_lua_directory(lua_dir: Path) -> list[LuaModule]:
    """Scan *lua_dir* for ``veaf*.lua`` files and extract id / version / var_name.

    ``var_name`` is the Lua variable prefix from the ``.Id`` assignment (e.g.
    ``"veafQraManager"`` from ``veafQraManager.Id = "QRA"`` in ``veafQraCore.lua``).
    It may differ from the filename stem when a module's public variable does not
    match its filename.
    """
    # group(1) = variable prefix, group(2) = ID string
    id_re = re.compile(r'\b(veaf\w+)\.Id\s*=\s*"([^"]+)"')
    ver_re = re.compile(r'\bveaf\w+\.Version\s*=\s*"([^"]+)"')
    modules: list[LuaModule] = []

    for lua_file in sorted(lua_dir.glob("veaf*.lua")):
        try:
            content = lua_file.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        id_match = id_re.search(content)
        ver_match = ver_re.search(content)
        if id_match:
            modules.append(
                LuaModule(
                    id=id_match.group(2),
                    version=ver_match.group(1) if ver_match else "",
                    filename=lua_file.name,
                    var_name=id_match.group(1),
                )
            )
    return modules


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def _validated_modules(raw: object, source: Path) -> list[LuaModule]:
    """Check a decoded module list and normalise its optional fields.

    VMR-061: the JSON was handed straight to the callers, so a stale or truncated file surfaced as a
    ``KeyError`` deep inside Lua emission instead of as a complaint about the file. The consumers did
    not even agree on the shape — ``lua_config_generator`` reads ``var_name`` directly where
    ``config_migrator`` treats it as optional — so it is normalised here and both see the same thing.

    Args:
        raw: Whatever ``json.loads`` produced.
        source: The file it came from, named in any error.

    Returns:
        The module list, with ``version`` and ``var_name`` filled in when absent.

    Raises:
        ValueError: If the payload is not a list of entries carrying an ``id`` and a ``filename``.
    """
    if not isinstance(raw, list):
        raise ValueError(t("modules.list_not_a_list", source=str(source), kind=type(raw).__name__))
    modules: list[LuaModule] = []
    for index, entry in enumerate(raw):
        if not isinstance(entry, dict):
            raise ValueError(t("modules.entry_not_a_table", source=str(source), index=index, kind=type(entry).__name__))
        for key in ("id", "filename"):
            if not entry.get(key):
                raise ValueError(t("modules.entry_missing_key", source=str(source), index=index, field=key))
        filename = str(entry["filename"])
        modules.append(
            LuaModule(
                id=str(entry["id"]),
                version=str(entry.get("version") or ""),
                filename=filename,
                var_name=str(entry.get("var_name") or filename.removesuffix(".lua")),
            )
        )
    return modules


def get_modules() -> list[LuaModule]:
    """Return the list of VEAF Lua modules.

    Sources tried in order:
    1. Bundled JSON (PyInstaller bundle at ``sys._MEIPASS``).
    2. Pre-generated JSON next to this module.
    3. Live scan of ``src/scripts/veaf/`` (repo checkout).

    Raises:
        ValueError: If a JSON source exists but does not hold a usable module list.
    """
    # 1. PyInstaller bundle
    path = _bundled_json_path()
    if path:
        return _validated_modules(json.loads(path.read_text(encoding="utf-8")), path)

    # 2. Pre-generated JSON
    path = _pregenerated_json_path()
    if path:
        return _validated_modules(json.loads(path.read_text(encoding="utf-8")), path)

    # 3. Live scan
    lua_dir = _find_lua_scripts_dir()
    if lua_dir:
        return _scan_lua_directory(lua_dir)

    return []


def generate_modules_json(output_path: Path, lua_dir: Path) -> int:
    """Scan *lua_dir* and write the modules list to *output_path* as JSON.

    Called by ``build-and-release.py`` before the PyInstaller compilation
    step so the resulting JSON can be bundled with ``--add-data``.

    Returns:
        Number of modules written.
    """
    modules = _scan_lua_directory(lua_dir)
    output_path.write_text(json.dumps(modules, indent=2, ensure_ascii=False), encoding="utf-8")
    return len(modules)


# ---------------------------------------------------------------------------
# Module config defaults scanning (LUA-004 / LUA-005)
# ---------------------------------------------------------------------------


def _extract_defaults(defaults_str: str) -> dict[str, bool]:
    """Parse boolean key=value pairs from a Lua table literal string."""
    result: dict[str, bool] = {}
    bool_re = re.compile(r"\b(\w+)\s*=\s*(true|false)\b")
    for m in bool_re.finditer(defaults_str):
        result[m.group(1)] = m.group(2) == "true"
    return result


def scan_module_configs(lua_dir: Path) -> dict[str, dict[str, bool]]:
    """Return a map of module-id → config defaults by scanning ``veaf.registerModule()`` calls.

    Parses the 3rd argument (defaults table) of each ``veaf.registerModule(...)`` call.
    Only boolean values are extracted (all current defaults are booleans).
    """
    id_re = re.compile(r"^\s*(\w+)\.Id\s*=\s*\"([^\"]+)\"", re.MULTILINE)
    # Match veaf.registerModule(xxx.Id, <initFn>, { key = value, ... }, order)
    # initFn is either a function()...end block or a simple reference.
    register_re = re.compile(
        r"veaf\.registerModule\s*\(\s*(\w+)\.Id\s*,"
        r"\s*(?:function\s*\(\s*\).*?end\s*,|[^,{]+,)\s*"
        r"\{([^}]+)\}",
        re.DOTALL,
    )

    result: dict[str, dict[str, bool]] = {}
    for lua_file in sorted(lua_dir.glob("veaf*.lua")):
        try:
            content = lua_file.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        id_map = {m.group(1): m.group(2) for m in id_re.finditer(content)}
        for m in register_re.finditer(content):
            module_id = id_map.get(m.group(1))
            if module_id:
                result[module_id] = _extract_defaults(m.group(2))

    return result


def find_lua_scripts_dir() -> Path | None:
    """Public wrapper: return the ``src/scripts/veaf`` directory or *None*."""
    return _find_lua_scripts_dir()


# ---------------------------------------------------------------------------
# Module initialisation scanning (CHORE-INIT-REGISTRY-TELLS-THE-TRUTH)
# ---------------------------------------------------------------------------
#
# `scan_module_configs` above answers "what defaults does this module declare?".
# `scan_module_initialisation` below answers "how does this module get started?":
# does it call `veaf.registerModule`, at which declared order, does it own an
# `initialize()` at all, and does it initialise itself when its file loads.
#
# It exists so a test can compare the Lua-side registry against the Python-side
# `_MODULE_INIT_ORDER` and fail when the two drift apart. See
# `docs/agents/module-initialisation.md`.


class ModuleInitFacts(TypedDict):
    """How one VEAF Lua module gets initialised, as read from its source."""

    id: str
    var_name: str  #: Lua table the module publishes, e.g. ``veafQraManager``
    filename: str
    registers: bool  #: the file calls ``veaf.registerModule(<var>.Id, …)``
    order: int | None  #: declared order; ``None`` when the module does not register
    wrapped: bool  #: initFn is an inline ``function() … end`` closure, not a bare function reference
    has_initialize: bool  #: the file defines ``function <var>.initialize(…)``
    init_params: str  #: that function's parameter list, verbatim (empty string when it takes none)
    self_initialises: bool  #: the file calls ``<var>.initialize(…)`` at load time, from the top level


def _strip_lua_comments(source: str) -> str:
    """Blank out Lua comments while preserving offsets and line count.

    Necessary rather than fussy: ``veafAirbases.lua`` and ``veafWeather.lua`` both keep a
    ``--[[ … ]]`` scratch block containing a top-level ``veafAirbases.initialize()``. Scanning
    the raw text reports two self-initialising modules that do no such thing.

    Args:
        source: Lua source text.

    Returns:
        The same text with every ``--`` line comment and ``--[[ … ]]`` long comment replaced by
        spaces, so line and column positions still match the original.
    """
    out: list[str] = []
    index, end_of_source = 0, len(source)
    while index < end_of_source:
        if source.startswith("--", index):
            long_open = re.match(r"--\[(=*)\[", source[index:])
            if long_open:
                closing = "]" + long_open.group(1) + "]"
                stop = source.find(closing, index + len(long_open.group(0)))
                stop = end_of_source if stop == -1 else stop + len(closing)
                out.append(re.sub(r"[^\n]", " ", source[index:stop]))
                index = stop
                continue
            stop = source.find("\n", index)
            stop = end_of_source if stop == -1 else stop
            out.append(" " * (stop - index))
            index = stop
            continue
        out.append(source[index])
        index += 1
    return "".join(out)


def _split_lua_args(argument_list: str) -> list[str]:
    """Split a Lua argument list on its top-level commas.

    A regular expression cannot do this: four registrations pass an inline
    ``function() … end`` closure whose body holds both commas and braces, and a pattern strict
    enough to skip them silently drops those four modules from the census.

    Args:
        argument_list: The text between a call's outer parentheses.

    Returns:
        The arguments, stripped, in order.
    """
    args: list[str] = []
    depth = 0
    current: list[str] = []
    for char in argument_list:
        if char in "({[":
            depth += 1
        elif char in ")}]":
            depth -= 1
        if char == "," and depth == 0:
            args.append("".join(current).strip())
            current = []
        else:
            current.append(char)
    if "".join(current).strip():
        args.append("".join(current).strip())
    return args


def _register_module_calls(source: str) -> list[list[str]]:
    """Return the argument list of every ``veaf.registerModule(...)`` call in *source*."""
    calls: list[list[str]] = []
    for match in re.finditer(r"veaf\.registerModule\s*\(", source):
        index = match.end()
        depth, start = 1, index
        while index < len(source) and depth:
            if source[index] == "(":
                depth += 1
            elif source[index] == ")":
                depth -= 1
            index += 1
        calls.append(_split_lua_args(source[start : index - 1]))
    return calls


def scan_module_initialisation(lua_dir: Path) -> dict[str, ModuleInitFacts]:
    """Return, for every VEAF Lua module in *lua_dir*, how it gets initialised.

    Every ``veaf*.lua`` file holding a ``<table>.Id = "…"`` line is reported, whether it
    registers or not — a module missing from the registry is exactly what the caller is
    looking for.

    Only registrations whose first argument is ``<table>.Id`` are counted, which is what
    excludes the two non-module call sites in ``veaf.lua``: the ``function veaf.registerModule(id,
    …)`` declaration itself, and the CTLD registration (``veaf.ctldId``) — CTLD is a community
    script, not a VEAF module, and the generator starts it from its own block.

    Args:
        lua_dir: The ``src/scripts/veaf`` directory.

    Returns:
        Module ID → :class:`ModuleInitFacts`.
    """
    id_assignment = re.compile(r"\b(veaf\w+)\.Id\s*=\s*\"([^\"]+)\"")
    facts: dict[str, ModuleInitFacts] = {}

    for lua_file in sorted(lua_dir.glob("veaf*.lua")):
        try:
            source = _strip_lua_comments(lua_file.read_text(encoding="utf-8", errors="ignore"))
        except OSError:
            continue
        id_match = id_assignment.search(source)
        if not id_match:
            continue
        var_name, module_id = id_match.group(1), id_match.group(2)
        signature = re.search(rf"function\s+{re.escape(var_name)}\.initialize\s*\(([^)]*)\)", source)
        entry = ModuleInitFacts(
            id=module_id,
            var_name=var_name,
            filename=lua_file.name,
            registers=False,
            order=None,
            wrapped=False,
            has_initialize=signature is not None,
            init_params=signature.group(1).strip() if signature else "",
            self_initialises=bool(re.search(rf"^{re.escape(var_name)}\.initialize\s*\(", source, re.MULTILINE)),
        )
        for args in _register_module_calls(source):
            if len(args) < 2 or args[0] != f"{var_name}.Id":
                continue
            order_arg = args[3] if len(args) > 3 else ""
            entry["registers"] = True
            entry["order"] = int(order_arg) if order_arg.isdigit() else 100
            entry["wrapped"] = args[1].startswith("function")
        facts[module_id] = entry

    return facts


def generate_modules_config_lua(
    lua_modules: dict[str, dict],
    header: str = "-- Generated by veaf-tools build from mission.yaml\n-- Do not edit manually.",
) -> str:
    """Backward-compatible wrapper — delegates to :func:`generate_config_lua`.

    *lua_modules* maps module IDs to dicts of ``{key: value}`` config overrides.
    """
    from veaf_libs.lua_config_generator import generate_config_lua  # noqa: PLC0415

    return generate_config_lua({"lua_modules": lua_modules}, header=header)


# ---------------------------------------------------------------------------
# Module YAML shorthand (FIX-CONVERT-V5-SILENT-LOSSES ticket 05)
# ---------------------------------------------------------------------------

#: Modules that are mandatory (infrastructure tier).
#: These are always active; specifying ``enable`` (true or false) for them is an error.
MANDATORY_MODULES: frozenset[str] = frozenset({"UNITS", "TIME", "CACHE", "EVENTS", "MARKERS", "COMMANDS"})


def yaml_module_entry(yaml_key: str, module_id: str, has_config: bool = False) -> list[str]:
    """Return the YAML lines for one enabled module entry in ``mission.yaml``.

    Lives here rather than in ``lua_config_generator`` so that importing the config **migrator**
    does not pull in the guided-checklist model and, through it, pydantic: the migrator needs this
    one helper and nothing else from the generator, and an outside harness importing
    ``ConfigMigrator`` as a library should not have to install a dependency it never uses (#725).
    ``lua_config_generator`` re-exports it, so existing importers are unaffected.

    Args:
        yaml_key: The (possibly quoted) YAML key string, e.g. ``RADIO`` or ``"MY-MOD"``.
        module_id: The canonical module ID used to look up mandatory status.
        has_config: When ``True``, emit block style (``key:\n  enabled: true``) so
            callers can append extra config keys underneath. When ``False`` (default),
            emit the compact shorthand ``key: true`` for optional modules.

    Returns:
        One line ``["  key:"]`` for mandatory modules (null value = always active),
        ``["  key: true"]`` for optional modules without extra config, or
        ``["  key:", "    enabled: true"]`` for optional modules with extra config.
    """
    if module_id in MANDATORY_MODULES:
        return [f"  {yaml_key}:"]
    if has_config:
        return [f"  {yaml_key}:", "    enabled: true"]
    return [f"  {yaml_key}: true"]
