"""The vendored DCS schema's ``country.id`` table must still agree with our own country table.

**Why this exists.** On 2026-09-19 a mission maker's build warning named country `68`. Resolving it
against ``dcs-countries.yaml`` gave USSR; the vendored schema's *other* country table, read as a
cross-check, gave the name belonging to 67. DCS has no country at id 14, and that second table
(``types["country.name"]``) renumbers its names sequentially instead of carrying the id across — so
everything after the hole slides down one slot and 78 of the 92 names are attached to the wrong id.
See ``.backlog/CHORE-SCHEMA-COUNTRY-NAMES-OFF-BY-ONE``.

**What this guards, and what it deliberately does not.** Only ``types["country.id"]`` is asserted:
it is correct today, it is the table a reader should use, and it is the one worth defending against a
future pin bump. ``types["country.name"]`` is left alone on purpose — asserting a known-wrong table
would encode the defect as intent and turn the day upstream repairs it into a red build.

The table is asserted **exhaustively**, every entry it carries rather than however many happen to
resolve. A test that silently resolved fewer and fewer names as spellings drift would keep passing
while guarding less and less, which is the failure mode its neighbour
``test_vendored_pins_match_the_files`` was written to avoid one level up.
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path

from veaf_libs.dcs_countries import all_country_ids, country_id_for_name

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "src/python/veaf-tools/veaf_libs/data/dcs-schema/dcs-world-api-schema.json"

# DCS spells five countries differently in the scripting API than in the datamined table — two of
# them are upstream typos (`OSETIA`, `CHEZH`) that ED has shipped for years, so they are mapped here
# rather than "fixed" anywhere. Every other name matches once underscores become spaces.
SCHEMA_NAME_ALIASES = {
    "AGGRESSORS": "USAF Aggressors",
    "SOUTH_OSETIA": "South Ossetia",
    "CHEZH_REPUBLIC": "Czech Republic",
    "THIRDREICH": "Third Reich",
    "UN_PEACEKEEPERS": "United Nations Peacekeepers",
}


def _schema_country_ids() -> dict[str, int]:
    """Return the vendored schema's name -> id country table.

    Returns:
        The ``types["country.id"].values`` mapping, as read from the vendored schema.
    """
    data = json.loads(SCHEMA.read_text(encoding="utf-8"))
    return data["types"]["country.id"]["values"]


class TestVendoredSchemaCountryIds(unittest.TestCase):
    def setUp(self) -> None:
        self.schema_ids = _schema_country_ids()

    def test_the_schema_still_carries_a_populated_country_table(self) -> None:
        """A pin bump that renames or drops the table must fail loudly, not quietly pass."""
        self.assertGreater(len(self.schema_ids), 50)

    def test_every_schema_country_resolves_in_our_table(self) -> None:
        """No name may go unresolved: an unresolvable one silently shrinks what the next test covers."""
        unresolved = [
            name
            for name in self.schema_ids
            if country_id_for_name(SCHEMA_NAME_ALIASES.get(name, name.replace("_", " "))) is None
        ]
        self.assertEqual(
            unresolved,
            [],
            "Unknown country spelling in the vendored schema — add it to SCHEMA_NAME_ALIASES",
        )

    def test_the_schema_ids_match_our_country_table(self) -> None:
        """This is the assertion the lot exists for: the id table is the trustworthy one."""
        mismatches = {
            name: (schema_id, country_id_for_name(SCHEMA_NAME_ALIASES.get(name, name.replace("_", " "))))
            for name, schema_id in self.schema_ids.items()
            if country_id_for_name(SCHEMA_NAME_ALIASES.get(name, name.replace("_", " "))) != schema_id
        }
        self.assertEqual(mismatches, {}, "Vendored schema and dcs-countries.yaml disagree (name: schema/ours)")

    def test_no_two_countries_share_an_id(self) -> None:
        """Matching ids are not enough if two names claim the same one — that is a broken table too."""
        ids = list(self.schema_ids.values())
        self.assertEqual(len(ids), len(set(ids)))

    def test_the_schema_knows_no_country_our_table_does_not(self) -> None:
        """Inclusion, not equality — and deliberately in this direction only.

        The two files are updated on independent schedules: `dcs-countries.yaml` is regenerated by the
        weekly DCS Data Drift Watcher, which opens its own PR, while the schema is frozen until someone
        bumps the pin by hand. So our table is the one that moves first, and asserting equality would
        turn the day ED adds a country into a red build on an unrelated automated PR — a failure with
        nothing to fix, on the side that is right. Both sets hold the same 92 ids today.
        """
        self.assertEqual(set(self.schema_ids.values()) - set(all_country_ids()), set())


if __name__ == "__main__":
    unittest.main()
