-- Regenerated by `veaf-tools build` from mission.yaml (custom_scripts:). Editing
-- it by hand has no lasting effect — declare your scripts in custom_scripts:.
local scriptsToLoad =
{
    "mission-script.lua",
}

if (VEAF_DYNAMIC_MISSIONPATH) then
    local sMissionScriptsPath = VEAF_DYNAMIC_MISSIONPATH .. [[src\scripts\]]
    for _, script in ipairs(scriptsToLoad) do
        local sPathToExec = sMissionScriptsPath .. script
        veaf.loggers.get(veaf.Id):info("DynamicConfig: loading " .. sPathToExec)
        assert(loadfile(sPathToExec))()
    end
else
    veaf.loggers.get(veaf.Id):error("DynamicConfig: cannot load because the VEAF_DYNAMIC_MISSIONPATH is not set")
end