"""Load spawn-data YAML and render it as a Lua module.

The YAML schema (see ``veaf_libs/data/veaf-units.yaml``):

```yaml
units:                                  # -> veafUnits.UnitsDatabase
  - aliases: [hq7]
    unitType: HQ-7_LN_SP
groups:                                 # -> veafUnits.GroupsDatabase
  - aliases: [sa2, sa-2]
    hidden: false                       # optional, default false
    disposition: {h: 6, w: 8}
    units:
      - {type: SNR_75V, cell: 20}
      - {type: ZSU_57_2, number: {min: 1, max: 2}, random: true}
    description: SA-2 SAM site
    groupName: SA2
```

The rendered Lua assigns ``veafUnits.UnitsDatabase`` / ``veafUnits.GroupsDatabase``;
it is loaded **after** the framework bundle (where the two tables now default to
empty), so it populates them. Lua tables are unordered for named keys, so the
emitter is free to use a canonical key order — only list order is preserved.
"""

from __future__ import annotations

from typing import Any

import yaml
from veaf_libs.bundled_data import read_bundled_text
from veaf_libs.lua_literals import lua_quoted_string

# Canonical order of named keys in a rendered group unit entry.
_UNIT_KEY_ORDER = ("cell", "hdg", "number", "size", "random", "fitToUnit")

_HEADER = (
    "-- AUTO-GENERATED by the veaf-tools spawn-data build step from veaf-units.yaml.\n"
    "-- Do not edit by hand; edit the YAML source instead. See ADR 0005.\n"
)


def load_framework_spawn_data() -> dict[str, Any]:
    """Load the shipped framework spawn data (``veaf-units.yaml``).

    Returns:
        A dict ``{"units": [...], "groups": [...]}`` (missing keys default to ``[]``).
    """
    raw = yaml.safe_load(read_bundled_text("veaf_libs", "data", "veaf-units.yaml")) or {}
    return {"units": raw.get("units") or [], "groups": raw.get("groups") or []}


def _lua_string(value: str) -> str:
    """Quote a string as a Lua string literal.

    Delegates to the shared helper.  This used to escape a backslash and a double quote
    and stop there, which left a newline — legal in a YAML unit name, a syntax error
    inside a Lua ``"…"`` string — to break the generated file (SECREV-2, VMR-010).

    The escaped short-string form, not the long-string one the mission config generator
    prefers: this output is read back by the bundled ``luadata`` parser, which does not
    implement long strings.
    """
    return lua_quoted_string(value)


def _lua_number(value: int | float) -> str:
    """Render a YAML number as Lua, collapsing integral floats (``10.0`` -> ``10``)."""
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _lua_scalar(value: Any) -> str:
    """Render a scalar (str/bool/int/float) as Lua source."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return _lua_number(value)
    if isinstance(value, str):
        return _lua_string(value)
    raise TypeError(f"unsupported scalar type: {type(value).__name__} ({value!r})")


def _lua_aliases(aliases: list[str]) -> str:
    """Render an alias list as a Lua array literal."""
    return "{ " + ", ".join(_lua_string(a) for a in aliases) + " }"


def _render_number(value: Any) -> str:
    """Render a unit ``number`` field (an int, or a ``{min, max}`` table)."""
    if isinstance(value, dict):
        rendered = f"{{ min = {int(value['min'])}, max = {int(value['max'])} }}"
        return rendered
    return str(int(value))


def _render_unit_entry(unit: dict[str, Any]) -> str:
    """Render one group unit: ``{ "TYPE", cell = N, ... }``."""
    parts = [_lua_string(unit["type"])]
    for key in _UNIT_KEY_ORDER:
        if key not in unit:
            continue
        value = unit[key]
        if key == "number":
            parts.append(f"number = {_render_number(value)}")
        else:
            parts.append(f"{key} = {_lua_scalar(value)}")
    return "{ " + ", ".join(parts) + " }"


def _render_unit_db_entry(entry: dict[str, Any], indent: str) -> str:
    """Render one ``UnitsDatabase`` entry."""
    rendered = f"{indent}{{ aliases = {_lua_aliases(entry['aliases'])}, unitType = {_lua_string(entry['unitType'])} }},"
    return rendered


def _render_group_entry(entry: dict[str, Any]) -> str:
    """Render one ``GroupsDatabase`` entry (with its nested ``group`` table)."""
    lines = ["  {", f"    aliases = {_lua_aliases(entry['aliases'])},"]
    if entry.get("hidden"):
        lines.append("    hidden = true,")
    lines.append("    group = {")
    disp = entry["disposition"]
    lines.append(f"      disposition = {{ h = {int(disp['h'])}, w = {int(disp['w'])} }},")
    lines.append("      units = {")
    for unit in entry["units"]:
        lines.append(f"        {_render_unit_entry(unit)},")
    lines.append("      },")
    if "description" in entry:
        lines.append(f"      description = {_lua_string(entry['description'])},")
    if "groupName" in entry:
        lines.append(f"      groupName = {_lua_string(entry['groupName'])},")
    lines.append("    },")
    lines.append("  },")
    return "\n".join(lines)


def render_spawn_data_lua(data: dict[str, Any]) -> str:
    """Render the spawn-data Lua module assigning the two ``veafUnits`` tables.

    Args:
        data: A ``{"units": [...], "groups": [...]}`` dict (the merged framework +
            mission spawn data).

    Returns:
        Lua source assigning ``veafUnits.UnitsDatabase`` and
        ``veafUnits.GroupsDatabase``.
    """
    units = data.get("units") or []
    groups = data.get("groups") or []

    out = [_HEADER, "veafUnits.UnitsDatabase = {"]
    out.extend(_render_unit_db_entry(u, "  ") for u in units)
    out.append("}")
    out.append("")
    out.append("veafUnits.GroupsDatabase = {")
    out.extend(_render_group_entry(g) for g in groups)
    out.append("}")
    out.append("")
    return "\n".join(out)
