"""Tests for the map-capture kit assembly (release artifact)."""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

import pytest

from veaf_build import kit

_BRIDGE_LUA = b"-- fake dcs-bridge.lua\n"


@pytest.fixture
def bridge_lua(tmp_path: Path) -> Path:
    p = tmp_path / "dcs-bridge.lua"
    p.write_bytes(_BRIDGE_LUA)
    return p


def test_build_bridge_mission_embeds_bridge_and_theatre(tmp_path: Path, bridge_lua: Path) -> None:
    out = kit.build_bridge_mission("Caucasus", tmp_path / "bridge-Caucasus.miz", bridge_lua)
    with zipfile.ZipFile(out) as miz:
        names = miz.namelist()
        assert any("dcs-bridge.lua" in n for n in names)
        mission = miz.read("mission").decode("utf-8")
    assert 'theatre = "Caucasus"' in mission
    assert "dcs-bridge loading" in mission  # the load trigger


def test_build_bridge_mission_leaves_no_backup_beside_it(tmp_path: Path, bridge_lua: Path) -> None:
    """The injection helper's timestamped backup must not pollute the kit."""
    out_dir = tmp_path / "missions"
    kit.build_bridge_mission("Caucasus", out_dir / "bridge-Caucasus.miz", bridge_lua)
    assert [p.name for p in out_dir.iterdir()] == ["bridge-Caucasus.miz"]


def test_build_bridge_missions_covers_requested_theatres(tmp_path: Path, bridge_lua: Path) -> None:
    written = kit.build_bridge_missions(tmp_path, bridge_lua, theatres=["Syria", "Caucasus"])
    assert [p.name for p in written] == ["bridge-Caucasus.miz", "bridge-Syria.miz"]  # sorted


def test_build_bridge_missions_defaults_to_every_supported_theatre(tmp_path: Path, bridge_lua: Path) -> None:
    from veaf_libs.blank_mission import supported_theatres

    written = kit.build_bridge_missions(tmp_path, bridge_lua)
    assert len(written) == len(supported_theatres())


def test_extract_dcs_serve(tmp_path: Path) -> None:
    zip_path = tmp_path / "dcs-bridge-1.0.0.zip"
    with zipfile.ZipFile(zip_path, "w") as zf:
        zf.writestr("dcs-serve.exe", b"MZ-fake")
        zf.writestr("dcs-client.exe", b"MZ-other")
    out = kit.extract_dcs_serve(zip_path, tmp_path / "staging")
    assert out.name == "dcs-serve.exe"
    assert out.read_bytes() == b"MZ-fake"


def test_extract_dcs_serve_missing_raises(tmp_path: Path) -> None:
    zip_path = tmp_path / "dcs-bridge-1.0.0.zip"
    with zipfile.ZipFile(zip_path, "w") as zf:
        zf.writestr("readme.txt", b"nothing here")
    with pytest.raises(RuntimeError, match="no dcs-serve.exe"):
        kit.extract_dcs_serve(zip_path, tmp_path / "staging")


def test_assemble_kit_contains_every_expected_member(tmp_path: Path, bridge_lua: Path) -> None:
    exe = tmp_path / "veaf-tools.exe"
    exe.write_bytes(b"MZ-tools")
    procedure = tmp_path / "capture-airbases.md"
    procedure.write_text("# how to", encoding="utf-8")
    bridge_zip = tmp_path / "dcs-bridge-1.0.0.zip"
    with zipfile.ZipFile(bridge_zip, "w") as zf:
        zf.writestr("dcs-serve.exe", b"MZ-serve")

    out = kit.assemble_kit(
        tmp_path / "stage",
        tmp_path / "kit.zip",
        veaf_tools_exe=exe,
        procedure_md=procedure,
        bridge_lua=bridge_lua,
        bridge_zip=bridge_zip,
    )

    with zipfile.ZipFile(out) as zf:
        names = zf.namelist()
        assert "veaf-tools.exe" in names
        assert "dcs-serve.exe" in names
        assert "PROCEDURE.md" in names
        assert any(n.startswith("missions/bridge-") and n.endswith(".miz") for n in names)
        # No secret is ever shipped: the key is generated by dcs-serve on first launch.
        assert not any("dcs-serve.yaml" in n for n in names)
        # The bundled missions are real .miz archives carrying the bridge.
        miz_name = next(n for n in names if n.startswith("missions/"))
        with zipfile.ZipFile(io.BytesIO(zf.read(miz_name))) as miz:
            assert any("dcs-bridge.lua" in n for n in miz.namelist())


def test_assemble_kit_without_bridge_zip_skips_the_server(tmp_path: Path, bridge_lua: Path) -> None:
    exe = tmp_path / "veaf-tools.exe"
    exe.write_bytes(b"MZ-tools")
    procedure = tmp_path / "p.md"
    procedure.write_text("x", encoding="utf-8")

    out = kit.assemble_kit(
        tmp_path / "stage",
        tmp_path / "kit.zip",
        veaf_tools_exe=exe,
        procedure_md=procedure,
        bridge_lua=bridge_lua,
    )

    with zipfile.ZipFile(out) as zf:
        assert "dcs-serve.exe" not in zf.namelist()
        assert "veaf-tools.exe" in zf.namelist()
